/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { LoginDto, LoginResponseDto } from "../../models";

import { customInstance } from "../api-client";

export const getAuth = () => {
  /**
   * @summary 用户登录
   */
  const authControllerLogin = (loginDto: LoginDto) => {
    return customInstance<LoginResponseDto>({
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginDto,
    });
  };
  /**
   * @summary 获取当前用户信息
   */
  const authControllerGetUserInfo = () => {
    return customInstance<LoginResponseDto>({ url: `/auth/me`, method: "GET" });
  };
  return { authControllerLogin, authControllerGetUserInfo };
};
export type AuthControllerLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerLogin"]>>
>;
export type AuthControllerGetUserInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerGetUserInfo"]>>
>;
