/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  BatchArchiveDto,
  BatchDeleteDto,
  BatchPublishDto,
  BatchUnpublishDto,
  CmsControllerFindAllContentsParams,
  CmsControllerFindAllPagesParams,
  CmsControllerGetArticlesParams,
  CmsControllerGetCasesParams,
  CmsControllerGetPageElementsParams,
  CmsControllerGetProductShowcasesParams,
  CmsControllerGetProfilesParams,
  CreateCmsContentDto,
  CreateCmsPageDto,
  CreateCmsTagDto,
  RestoreVersionDto,
  UpdateCmsContentDto,
  UpdateCmsPageDto,
  UpdateCmsTagDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getCms = () => {
  /**
   * @summary 创建内容
   */
  const cmsControllerCreateContent = (
    createCmsContentDto: CreateCmsContentDto,
  ) => {
    return customInstance<void>({
      url: `/cms/contents`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCmsContentDto,
    });
  };
  /**
   * @summary 获取内容列表
   */
  const cmsControllerFindAllContents = (
    params?: CmsControllerFindAllContentsParams,
  ) => {
    return customInstance<void>({
      url: `/cms/contents`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取内容详情
   */
  const cmsControllerFindOneContent = (id: string) => {
    return customInstance<void>({ url: `/cms/contents/${id}`, method: "GET" });
  };
  /**
   * @summary 更新内容
   */
  const cmsControllerUpdateContent = (
    id: string,
    updateCmsContentDto: UpdateCmsContentDto,
  ) => {
    return customInstance<void>({
      url: `/cms/contents/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCmsContentDto,
    });
  };
  /**
   * @summary 删除内容
   */
  const cmsControllerDeleteContent = (id: string) => {
    return customInstance<void>({
      url: `/cms/contents/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 发布内容
   */
  const cmsControllerPublishContent = (id: string) => {
    return customInstance<void>({
      url: `/cms/contents/${id}/publish`,
      method: "POST",
    });
  };
  /**
   * @summary 取消发布内容
   */
  const cmsControllerUnpublishContent = (id: string) => {
    return customInstance<void>({
      url: `/cms/contents/${id}/unpublish`,
      method: "POST",
    });
  };
  /**
   * @summary 获取文章列表
   */
  const cmsControllerGetArticles = (
    params?: CmsControllerGetArticlesParams,
  ) => {
    return customInstance<void>({
      url: `/cms/articles`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取案例列表
   */
  const cmsControllerGetCases = (params?: CmsControllerGetCasesParams) => {
    return customInstance<void>({ url: `/cms/cases`, method: "GET", params });
  };
  /**
   * @summary 获取产品展示列表
   */
  const cmsControllerGetProductShowcases = (
    params?: CmsControllerGetProductShowcasesParams,
  ) => {
    return customInstance<void>({
      url: `/cms/product-showcases`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取人员介绍列表
   */
  const cmsControllerGetProfiles = (
    params?: CmsControllerGetProfilesParams,
  ) => {
    return customInstance<void>({
      url: `/cms/profiles`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取页面元素列表
   */
  const cmsControllerGetPageElements = (
    params?: CmsControllerGetPageElementsParams,
  ) => {
    return customInstance<void>({
      url: `/cms/page-elements`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取所有标签
   */
  const cmsControllerFindAllTags = () => {
    return customInstance<void>({ url: `/cms/tags`, method: "GET" });
  };
  /**
   * @summary 创建标签
   */
  const cmsControllerCreateTag = (createCmsTagDto: CreateCmsTagDto) => {
    return customInstance<void>({
      url: `/cms/tags`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCmsTagDto,
    });
  };
  /**
   * @summary 获取标签详情
   */
  const cmsControllerFindOneTag = (id: string) => {
    return customInstance<void>({ url: `/cms/tags/${id}`, method: "GET" });
  };
  /**
   * @summary 更新标签
   */
  const cmsControllerUpdateTag = (
    id: string,
    updateCmsTagDto: UpdateCmsTagDto,
  ) => {
    return customInstance<void>({
      url: `/cms/tags/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCmsTagDto,
    });
  };
  /**
   * @summary 删除标签
   */
  const cmsControllerDeleteTag = (id: string) => {
    return customInstance<void>({ url: `/cms/tags/${id}`, method: "DELETE" });
  };
  /**
   * @summary 创建页面
   */
  const cmsControllerCreatePage = (createCmsPageDto: CreateCmsPageDto) => {
    return customInstance<void>({
      url: `/cms/pages`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCmsPageDto,
    });
  };
  /**
   * @summary 获取页面列表
   */
  const cmsControllerFindAllPages = (
    params?: CmsControllerFindAllPagesParams,
  ) => {
    return customInstance<void>({ url: `/cms/pages`, method: "GET", params });
  };
  /**
   * @summary 获取页面详情
   */
  const cmsControllerFindOnePage = (id: string) => {
    return customInstance<void>({ url: `/cms/pages/${id}`, method: "GET" });
  };
  /**
   * @summary 更新页面
   */
  const cmsControllerUpdatePage = (
    id: string,
    updateCmsPageDto: UpdateCmsPageDto,
  ) => {
    return customInstance<void>({
      url: `/cms/pages/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCmsPageDto,
    });
  };
  /**
   * @summary 删除页面
   */
  const cmsControllerDeletePage = (id: string) => {
    return customInstance<void>({ url: `/cms/pages/${id}`, method: "DELETE" });
  };
  /**
   * @summary 发布页面
   */
  const cmsControllerPublishPage = (id: string) => {
    return customInstance<void>({
      url: `/cms/pages/${id}/publish`,
      method: "POST",
    });
  };
  /**
   * @summary 取消发布页面
   */
  const cmsControllerUnpublishPage = (id: string) => {
    return customInstance<void>({
      url: `/cms/pages/${id}/unpublish`,
      method: "POST",
    });
  };
  /**
   * @summary 生成内容预览令牌
   */
  const cmsControllerGenerateContentPreviewToken = (id: string) => {
    return customInstance<void>({
      url: `/cms/contents/${id}/preview-token`,
      method: "POST",
    });
  };
  /**
   * @summary 生成页面预览令牌
   */
  const cmsControllerGeneratePagePreviewToken = (id: string) => {
    return customInstance<void>({
      url: `/cms/pages/${id}/preview-token`,
      method: "POST",
    });
  };
  /**
   * @summary 获取内容版本历史
   */
  const cmsControllerGetContentVersions = (id: string) => {
    return customInstance<void>({
      url: `/cms/contents/${id}/versions`,
      method: "GET",
    });
  };
  /**
   * @summary 获取特定版本详情
   */
  const cmsControllerGetContentVersionDetail = (
    id: string,
    versionId: string,
  ) => {
    return customInstance<void>({
      url: `/cms/contents/${id}/versions/${versionId}`,
      method: "GET",
    });
  };
  /**
   * @summary 恢复到指定版本
   */
  const cmsControllerRestoreContentVersion = (
    id: string,
    versionId: string,
    restoreVersionDto: RestoreVersionDto,
  ) => {
    return customInstance<void>({
      url: `/cms/contents/${id}/restore/${versionId}`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: restoreVersionDto,
    });
  };
  /**
   * @summary 批量发布内容
   */
  const cmsControllerBatchPublishContents = (
    batchPublishDto: BatchPublishDto,
  ) => {
    return customInstance<void>({
      url: `/cms/contents/batch/publish`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchPublishDto,
    });
  };
  /**
   * @summary 批量取消发布内容
   */
  const cmsControllerBatchUnpublishContents = (
    batchUnpublishDto: BatchUnpublishDto,
  ) => {
    return customInstance<void>({
      url: `/cms/contents/batch/unpublish`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchUnpublishDto,
    });
  };
  /**
   * @summary 批量删除内容
   */
  const cmsControllerBatchDeleteContents = (batchDeleteDto: BatchDeleteDto) => {
    return customInstance<void>({
      url: `/cms/contents/batch/delete`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchDeleteDto,
    });
  };
  /**
   * @summary 批量归档内容
   */
  const cmsControllerBatchArchiveContents = (
    batchArchiveDto: BatchArchiveDto,
  ) => {
    return customInstance<void>({
      url: `/cms/contents/batch/archive`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchArchiveDto,
    });
  };
  /**
   * @summary 批量发布页面
   */
  const cmsControllerBatchPublishPages = (batchPublishDto: BatchPublishDto) => {
    return customInstance<void>({
      url: `/cms/pages/batch/publish`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchPublishDto,
    });
  };
  /**
   * @summary 批量取消发布页面
   */
  const cmsControllerBatchUnpublishPages = (
    batchUnpublishDto: BatchUnpublishDto,
  ) => {
    return customInstance<void>({
      url: `/cms/pages/batch/unpublish`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchUnpublishDto,
    });
  };
  /**
   * @summary 批量删除页面
   */
  const cmsControllerBatchDeletePages = (batchDeleteDto: BatchDeleteDto) => {
    return customInstance<void>({
      url: `/cms/pages/batch/delete`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchDeleteDto,
    });
  };
  return {
    cmsControllerCreateContent,
    cmsControllerFindAllContents,
    cmsControllerFindOneContent,
    cmsControllerUpdateContent,
    cmsControllerDeleteContent,
    cmsControllerPublishContent,
    cmsControllerUnpublishContent,
    cmsControllerGetArticles,
    cmsControllerGetCases,
    cmsControllerGetProductShowcases,
    cmsControllerGetProfiles,
    cmsControllerGetPageElements,
    cmsControllerFindAllTags,
    cmsControllerCreateTag,
    cmsControllerFindOneTag,
    cmsControllerUpdateTag,
    cmsControllerDeleteTag,
    cmsControllerCreatePage,
    cmsControllerFindAllPages,
    cmsControllerFindOnePage,
    cmsControllerUpdatePage,
    cmsControllerDeletePage,
    cmsControllerPublishPage,
    cmsControllerUnpublishPage,
    cmsControllerGenerateContentPreviewToken,
    cmsControllerGeneratePagePreviewToken,
    cmsControllerGetContentVersions,
    cmsControllerGetContentVersionDetail,
    cmsControllerRestoreContentVersion,
    cmsControllerBatchPublishContents,
    cmsControllerBatchUnpublishContents,
    cmsControllerBatchDeleteContents,
    cmsControllerBatchArchiveContents,
    cmsControllerBatchPublishPages,
    cmsControllerBatchUnpublishPages,
    cmsControllerBatchDeletePages,
  };
};
export type CmsControllerCreateContentResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerCreateContent"]>>
>;
export type CmsControllerFindAllContentsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerFindAllContents"]>>
>;
export type CmsControllerFindOneContentResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerFindOneContent"]>>
>;
export type CmsControllerUpdateContentResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerUpdateContent"]>>
>;
export type CmsControllerDeleteContentResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerDeleteContent"]>>
>;
export type CmsControllerPublishContentResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerPublishContent"]>>
>;
export type CmsControllerUnpublishContentResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerUnpublishContent"]>
  >
>;
export type CmsControllerGetArticlesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerGetArticles"]>>
>;
export type CmsControllerGetCasesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerGetCases"]>>
>;
export type CmsControllerGetProductShowcasesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerGetProductShowcases"]>
  >
>;
export type CmsControllerGetProfilesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerGetProfiles"]>>
>;
export type CmsControllerGetPageElementsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerGetPageElements"]>>
>;
export type CmsControllerFindAllTagsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerFindAllTags"]>>
>;
export type CmsControllerCreateTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerCreateTag"]>>
>;
export type CmsControllerFindOneTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerFindOneTag"]>>
>;
export type CmsControllerUpdateTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerUpdateTag"]>>
>;
export type CmsControllerDeleteTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerDeleteTag"]>>
>;
export type CmsControllerCreatePageResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerCreatePage"]>>
>;
export type CmsControllerFindAllPagesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerFindAllPages"]>>
>;
export type CmsControllerFindOnePageResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerFindOnePage"]>>
>;
export type CmsControllerUpdatePageResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerUpdatePage"]>>
>;
export type CmsControllerDeletePageResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerDeletePage"]>>
>;
export type CmsControllerPublishPageResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerPublishPage"]>>
>;
export type CmsControllerUnpublishPageResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerUnpublishPage"]>>
>;
export type CmsControllerGenerateContentPreviewTokenResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCms>["cmsControllerGenerateContentPreviewToken"]
    >
  >
>;
export type CmsControllerGeneratePagePreviewTokenResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCms>["cmsControllerGeneratePagePreviewToken"]
    >
  >
>;
export type CmsControllerGetContentVersionsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerGetContentVersions"]>
  >
>;
export type CmsControllerGetContentVersionDetailResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCms>["cmsControllerGetContentVersionDetail"]
    >
  >
>;
export type CmsControllerRestoreContentVersionResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerRestoreContentVersion"]>
  >
>;
export type CmsControllerBatchPublishContentsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerBatchPublishContents"]>
  >
>;
export type CmsControllerBatchUnpublishContentsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerBatchUnpublishContents"]>
  >
>;
export type CmsControllerBatchDeleteContentsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerBatchDeleteContents"]>
  >
>;
export type CmsControllerBatchArchiveContentsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerBatchArchiveContents"]>
  >
>;
export type CmsControllerBatchPublishPagesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerBatchPublishPages"]>
  >
>;
export type CmsControllerBatchUnpublishPagesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerBatchUnpublishPages"]>
  >
>;
export type CmsControllerBatchDeletePagesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerBatchDeletePages"]>
  >
>;
