/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  ContractControllerFindAllParams,
  CreateContractDto,
  UpdateContractDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getContracts = () => {
  /**
   * @summary 创建合同
   */
  const contractControllerCreate = (createContractDto: CreateContractDto) => {
    return customInstance<void>({
      url: `/contracts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createContractDto,
    });
  };
  /**
   * @summary 获取合同列表
   */
  const contractControllerFindAll = (
    params?: ContractControllerFindAllParams,
  ) => {
    return customInstance<void>({ url: `/contracts`, method: "GET", params });
  };
  /**
   * @summary 获取合同详情
   */
  const contractControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/contracts/${id}`, method: "GET" });
  };
  /**
   * @summary 更新合同
   */
  const contractControllerUpdate = (
    id: string,
    updateContractDto: UpdateContractDto,
  ) => {
    return customInstance<void>({
      url: `/contracts/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateContractDto,
    });
  };
  /**
   * @summary 删除合同
   */
  const contractControllerRemove = (id: string) => {
    return customInstance<void>({ url: `/contracts/${id}`, method: "DELETE" });
  };
  /**
   * @summary 更新合同收款状态
   */
  const contractControllerUpdatePaymentStatus = (id: string) => {
    return customInstance<void>({
      url: `/contracts/${id}/update-payment-status`,
      method: "POST",
    });
  };
  return {
    contractControllerCreate,
    contractControllerFindAll,
    contractControllerFindOne,
    contractControllerUpdate,
    contractControllerRemove,
    contractControllerUpdatePaymentStatus,
  };
};
export type ContractControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getContracts>["contractControllerCreate"]>
  >
>;
export type ContractControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getContracts>["contractControllerFindAll"]>
  >
>;
export type ContractControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getContracts>["contractControllerFindOne"]>
  >
>;
export type ContractControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getContracts>["contractControllerUpdate"]>
  >
>;
export type ContractControllerRemoveResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getContracts>["contractControllerRemove"]>
  >
>;
export type ContractControllerUpdatePaymentStatusResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getContracts>["contractControllerUpdatePaymentStatus"]
    >
  >
>;
