/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  ContactControllerFindAllParams,
  CreateContactDto,
  LinkCompanyDto,
  UpdateContactDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getContacts = () => {
  /**
   * @summary 创建联系人
   */
  const contactControllerCreate = (createContactDto: CreateContactDto) => {
    return customInstance<void>({
      url: `/contacts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createContactDto,
    });
  };
  /**
   * @summary 查询联系人列表
   */
  const contactControllerFindAll = (
    params?: ContactControllerFindAllParams,
  ) => {
    return customInstance<void>({ url: `/contacts`, method: "GET", params });
  };
  /**
   * @summary 获取联系人详情
   */
  const contactControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/contacts/${id}`, method: "GET" });
  };
  /**
   * @summary 更新联系人
   */
  const contactControllerUpdate = (
    id: string,
    updateContactDto: UpdateContactDto,
  ) => {
    return customInstance<void>({
      url: `/contacts/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateContactDto,
    });
  };
  /**
   * @summary 删除联系人
   */
  const contactControllerRemove = (id: string) => {
    return customInstance<void>({ url: `/contacts/${id}`, method: "DELETE" });
  };
  /**
   * @summary 通过手机号查找联系人
   */
  const contactControllerFindByPhone = (phone: string) => {
    return customInstance<void>({
      url: `/contacts/phone/${phone}`,
      method: "GET",
    });
  };
  /**
   * @summary 关联公司
   */
  const contactControllerLinkCompany = (
    id: string,
    linkCompanyDto: LinkCompanyDto,
  ) => {
    return customInstance<void>({
      url: `/contacts/${id}/companies`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: linkCompanyDto,
    });
  };
  /**
   * @summary 取消关联公司
   */
  const contactControllerUnlinkCompany = (id: string, customerId: string) => {
    return customInstance<void>({
      url: `/contacts/${id}/companies/${customerId}`,
      method: "DELETE",
    });
  };
  return {
    contactControllerCreate,
    contactControllerFindAll,
    contactControllerFindOne,
    contactControllerUpdate,
    contactControllerRemove,
    contactControllerFindByPhone,
    contactControllerLinkCompany,
    contactControllerUnlinkCompany,
  };
};
export type ContactControllerCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getContacts>["contactControllerCreate"]>>
>;
export type ContactControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getContacts>["contactControllerFindAll"]>
  >
>;
export type ContactControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getContacts>["contactControllerFindOne"]>
  >
>;
export type ContactControllerUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getContacts>["contactControllerUpdate"]>>
>;
export type ContactControllerRemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getContacts>["contactControllerRemove"]>>
>;
export type ContactControllerFindByPhoneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getContacts>["contactControllerFindByPhone"]>
  >
>;
export type ContactControllerLinkCompanyResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getContacts>["contactControllerLinkCompany"]>
  >
>;
export type ContactControllerUnlinkCompanyResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getContacts>["contactControllerUnlinkCompany"]>
  >
>;
