/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateContractTemplateDto,
  PreviewContractTemplateDto,
  UpdateContractTemplateDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getContractTemplates = () => {
  /**
   * @summary 获取所有合同模板
   */
  const contractTemplateControllerFindAll = () => {
    return customInstance<void>({ url: `/contract-templates`, method: "GET" });
  };
  /**
   * @summary 创建合同模板
   */
  const contractTemplateControllerCreate = (
    createContractTemplateDto: CreateContractTemplateDto,
  ) => {
    return customInstance<void>({
      url: `/contract-templates`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createContractTemplateDto,
    });
  };
  /**
   * @summary 获取模板详情
   */
  const contractTemplateControllerFindOne = (id: string) => {
    return customInstance<void>({
      url: `/contract-templates/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 更新合同模板
   */
  const contractTemplateControllerUpdate = (
    id: string,
    updateContractTemplateDto: UpdateContractTemplateDto,
  ) => {
    return customInstance<void>({
      url: `/contract-templates/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateContractTemplateDto,
    });
  };
  /**
   * @summary 删除合同模板
   */
  const contractTemplateControllerRemove = (id: string) => {
    return customInstance<void>({
      url: `/contract-templates/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 获取模板变量定义
   */
  const contractTemplateControllerGetVariables = (id: string) => {
    return customInstance<void>({
      url: `/contract-templates/${id}/variables`,
      method: "GET",
    });
  };
  /**
   * @summary 预览合同（替换变量）
   */
  const contractTemplateControllerPreview = (
    id: string,
    previewContractTemplateDto: PreviewContractTemplateDto,
  ) => {
    return customInstance<void>({
      url: `/contract-templates/${id}/preview`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: previewContractTemplateDto,
    });
  };
  return {
    contractTemplateControllerFindAll,
    contractTemplateControllerCreate,
    contractTemplateControllerFindOne,
    contractTemplateControllerUpdate,
    contractTemplateControllerRemove,
    contractTemplateControllerGetVariables,
    contractTemplateControllerPreview,
  };
};
export type ContractTemplateControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getContractTemplates
      >["contractTemplateControllerFindAll"]
    >
  >
>;
export type ContractTemplateControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getContractTemplates
      >["contractTemplateControllerCreate"]
    >
  >
>;
export type ContractTemplateControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getContractTemplates
      >["contractTemplateControllerFindOne"]
    >
  >
>;
export type ContractTemplateControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getContractTemplates
      >["contractTemplateControllerUpdate"]
    >
  >
>;
export type ContractTemplateControllerRemoveResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getContractTemplates
      >["contractTemplateControllerRemove"]
    >
  >
>;
export type ContractTemplateControllerGetVariablesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getContractTemplates
      >["contractTemplateControllerGetVariables"]
    >
  >
>;
export type ContractTemplateControllerPreviewResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getContractTemplates
      >["contractTemplateControllerPreview"]
    >
  >
>;
