/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  AddContactDto,
  LinkContactDto,
  UpdateContactRoleDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getCustomerContacts = () => {
  /**
   * @summary 为公司添加联系人（不存在则创建）
   */
  const customerContactControllerAddContact = (
    customerId: string,
    addContactDto: AddContactDto,
  ) => {
    return customInstance<void>({
      url: `/customers/${customerId}/contacts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: addContactDto,
    });
  };
  /**
   * @summary 获取公司的所有联系人
   */
  const customerContactControllerGetCustomerContacts = (customerId: string) => {
    return customInstance<void>({
      url: `/customers/${customerId}/contacts`,
      method: "GET",
    });
  };
  /**
   * @summary 关联已有联系人
   */
  const customerContactControllerLinkContact = (
    customerId: string,
    linkContactDto: LinkContactDto,
  ) => {
    return customInstance<void>({
      url: `/customers/${customerId}/contacts/link`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: linkContactDto,
    });
  };
  /**
   * @summary 更新联系人角色
   */
  const customerContactControllerUpdateContactRole = (
    customerId: string,
    contactId: string,
    updateContactRoleDto: UpdateContactRoleDto,
  ) => {
    return customInstance<void>({
      url: `/customers/${customerId}/contacts/${contactId}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateContactRoleDto,
    });
  };
  /**
   * @summary 取消关联（标记为离职）
   */
  const customerContactControllerUnlinkContact = (
    customerId: string,
    contactId: string,
  ) => {
    return customInstance<void>({
      url: `/customers/${customerId}/contacts/${contactId}`,
      method: "DELETE",
    });
  };
  return {
    customerContactControllerAddContact,
    customerContactControllerGetCustomerContacts,
    customerContactControllerLinkContact,
    customerContactControllerUpdateContactRole,
    customerContactControllerUnlinkContact,
  };
};
export type CustomerContactControllerAddContactResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getCustomerContacts
      >["customerContactControllerAddContact"]
    >
  >
>;
export type CustomerContactControllerGetCustomerContactsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getCustomerContacts
      >["customerContactControllerGetCustomerContacts"]
    >
  >
>;
export type CustomerContactControllerLinkContactResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getCustomerContacts
      >["customerContactControllerLinkContact"]
    >
  >
>;
export type CustomerContactControllerUpdateContactRoleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getCustomerContacts
      >["customerContactControllerUpdateContactRole"]
    >
  >
>;
export type CustomerContactControllerUnlinkContactResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getCustomerContacts
      >["customerContactControllerUnlinkContact"]
    >
  >
>;
