/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  AssignDto,
  BatchAssignDto,
  BatchDeleteCustomersDto,
  BatchTagsCustomersDto,
  BatchUpdateCustomersDto,
  CreateCustomerDto,
  CustomerControllerExportCustomersParams,
  CustomerControllerFindAllParams,
  UpdateCustomerDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getCustomers = () => {
  /**
   * @summary 创建客户
   */
  const customerControllerCreate = (createCustomerDto: CreateCustomerDto) => {
    return customInstance<void>({
      url: `/customers`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCustomerDto,
    });
  };
  /**
   * @summary 获取客户列表
   */
  const customerControllerFindAll = (
    params?: CustomerControllerFindAllParams,
  ) => {
    return customInstance<void>({ url: `/customers`, method: "GET", params });
  };
  /**
   * @summary 获取客户详情
   */
  const customerControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/customers/${id}`, method: "GET" });
  };
  /**
   * @summary 更新客户
   */
  const customerControllerUpdate = (
    id: string,
    updateCustomerDto: UpdateCustomerDto,
  ) => {
    return customInstance<void>({
      url: `/customers/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCustomerDto,
    });
  };
  /**
   * @summary 删除客户
   */
  const customerControllerRemove = (id: string) => {
    return customInstance<void>({ url: `/customers/${id}`, method: "DELETE" });
  };
  /**
   * @summary 分配单个客户
   */
  const customerControllerAssignOne = (id: string, assignDto: AssignDto) => {
    return customInstance<void>({
      url: `/customers/${id}/assign`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: assignDto,
    });
  };
  /**
   * @summary 批量分配客户
   */
  const customerControllerBatchAssign = (batchAssignDto: BatchAssignDto) => {
    return customInstance<void>({
      url: `/customers/batch-assign`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: batchAssignDto,
    });
  };
  /**
   * @summary 批量更新客户
   */
  const customerControllerBatchUpdate = (
    batchUpdateCustomersDto: BatchUpdateCustomersDto,
  ) => {
    return customInstance<void>({
      url: `/customers/batch-update`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: batchUpdateCustomersDto,
    });
  };
  /**
   * @summary 批量删除客户
   */
  const customerControllerBatchDelete = (
    batchDeleteCustomersDto: BatchDeleteCustomersDto,
  ) => {
    return customInstance<void>({
      url: `/customers/batch-delete`,
      method: "DELETE",
      headers: { "Content-Type": "application/json" },
      data: batchDeleteCustomersDto,
    });
  };
  /**
   * @summary 批量管理客户标签
   */
  const customerControllerBatchTags = (
    batchTagsCustomersDto: BatchTagsCustomersDto,
  ) => {
    return customInstance<void>({
      url: `/customers/batch-tags`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: batchTagsCustomersDto,
    });
  };
  /**
   * @summary 查询客户分配历史
   */
  const customerControllerGetAssignmentHistory = (id: string) => {
    return customInstance<void>({
      url: `/customers/${id}/assignment-history`,
      method: "GET",
    });
  };
  /**
   * @summary 查询客户跟进记录
   */
  const customerControllerGetFollowRecords = (id: string) => {
    return customInstance<void>({
      url: `/customers/${id}/follow-records`,
      method: "GET",
    });
  };
  /**
   * @summary 批量导入客户
   */
  const customerControllerImportCustomers = () => {
    return customInstance<void>({ url: `/customers/import`, method: "POST" });
  };
  /**
   * @summary 导出客户数据
   */
  const customerControllerExportCustomers = (
    params?: CustomerControllerExportCustomersParams,
  ) => {
    return customInstance<void>({
      url: `/customers/export`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 下载客户导入模板
   */
  const customerControllerDownloadImportTemplate = () => {
    return customInstance<void>({
      url: `/customers/import-template`,
      method: "GET",
    });
  };
  /**
   * @summary 客户等级分布统计
   */
  const customerControllerGetLevelDistribution = () => {
    return customInstance<void>({
      url: `/customers/statistics/level-distribution`,
      method: "GET",
    });
  };
  /**
   * @summary 客户转化率分析
   */
  const customerControllerGetConversionRate = () => {
    return customInstance<void>({
      url: `/customers/statistics/conversion-rate`,
      method: "GET",
    });
  };
  /**
   * @summary 客户增长趋势
   */
  const customerControllerGetGrowthTrend = () => {
    return customInstance<void>({
      url: `/customers/statistics/growth-trend`,
      method: "GET",
    });
  };
  return {
    customerControllerCreate,
    customerControllerFindAll,
    customerControllerFindOne,
    customerControllerUpdate,
    customerControllerRemove,
    customerControllerAssignOne,
    customerControllerBatchAssign,
    customerControllerBatchUpdate,
    customerControllerBatchDelete,
    customerControllerBatchTags,
    customerControllerGetAssignmentHistory,
    customerControllerGetFollowRecords,
    customerControllerImportCustomers,
    customerControllerExportCustomers,
    customerControllerDownloadImportTemplate,
    customerControllerGetLevelDistribution,
    customerControllerGetConversionRate,
    customerControllerGetGrowthTrend,
  };
};
export type CustomerControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerCreate"]>
  >
>;
export type CustomerControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerFindAll"]>
  >
>;
export type CustomerControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerFindOne"]>
  >
>;
export type CustomerControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerUpdate"]>
  >
>;
export type CustomerControllerRemoveResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerRemove"]>
  >
>;
export type CustomerControllerAssignOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerAssignOne"]>
  >
>;
export type CustomerControllerBatchAssignResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerBatchAssign"]>
  >
>;
export type CustomerControllerBatchUpdateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerBatchUpdate"]>
  >
>;
export type CustomerControllerBatchDeleteResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerBatchDelete"]>
  >
>;
export type CustomerControllerBatchTagsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerBatchTags"]>
  >
>;
export type CustomerControllerGetAssignmentHistoryResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomers>["customerControllerGetAssignmentHistory"]
    >
  >
>;
export type CustomerControllerGetFollowRecordsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomers>["customerControllerGetFollowRecords"]
    >
  >
>;
export type CustomerControllerImportCustomersResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomers>["customerControllerImportCustomers"]
    >
  >
>;
export type CustomerControllerExportCustomersResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomers>["customerControllerExportCustomers"]
    >
  >
>;
export type CustomerControllerDownloadImportTemplateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getCustomers
      >["customerControllerDownloadImportTemplate"]
    >
  >
>;
export type CustomerControllerGetLevelDistributionResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomers>["customerControllerGetLevelDistribution"]
    >
  >
>;
export type CustomerControllerGetConversionRateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomers>["customerControllerGetConversionRate"]
    >
  >
>;
export type CustomerControllerGetGrowthTrendResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomers>["customerControllerGetGrowthTrend"]
    >
  >
>;
