/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateCustomerRuleDto,
  CustomerRuleResponse,
  InitializeResultResponse,
  UpdateCustomerRuleDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getCustomerRules = () => {
  /**
   * @summary 获取所有客户规则
   */
  const customerRuleControllerFindAll = () => {
    return customInstance<CustomerRuleResponse[]>({
      url: `/customer-rules`,
      method: "GET",
    });
  };
  /**
   * @summary 创建新规则（仅用于初始化预设规则）
   */
  const customerRuleControllerCreate = (
    createCustomerRuleDto: CreateCustomerRuleDto,
  ) => {
    return customInstance<CustomerRuleResponse>({
      url: `/customer-rules`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCustomerRuleDto,
    });
  };
  /**
   * @summary 通过 code 获取规则
   */
  const customerRuleControllerFindByCode = (code: string) => {
    return customInstance<CustomerRuleResponse>({
      url: `/customer-rules/code/${code}`,
      method: "GET",
    });
  };
  /**
   * @summary 获取单个规则（通过 ID）
   */
  const customerRuleControllerFindOne = (id: string) => {
    return customInstance<CustomerRuleResponse>({
      url: `/customer-rules/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 更新规则
   */
  const customerRuleControllerUpdate = (
    id: string,
    updateCustomerRuleDto: UpdateCustomerRuleDto,
  ) => {
    return customInstance<CustomerRuleResponse>({
      url: `/customer-rules/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCustomerRuleDto,
    });
  };
  /**
   * @summary 删除规则
   */
  const customerRuleControllerRemove = (id: string) => {
    return customInstance<CustomerRuleResponse>({
      url: `/customer-rules/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 初始化预设规则
   */
  const customerRuleControllerInitializeDefaultRules = () => {
    return customInstance<InitializeResultResponse[]>({
      url: `/customer-rules/initialize`,
      method: "POST",
    });
  };
  return {
    customerRuleControllerFindAll,
    customerRuleControllerCreate,
    customerRuleControllerFindByCode,
    customerRuleControllerFindOne,
    customerRuleControllerUpdate,
    customerRuleControllerRemove,
    customerRuleControllerInitializeDefaultRules,
  };
};
export type CustomerRuleControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomerRules>["customerRuleControllerFindAll"]
    >
  >
>;
export type CustomerRuleControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomerRules>["customerRuleControllerCreate"]
    >
  >
>;
export type CustomerRuleControllerFindByCodeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomerRules>["customerRuleControllerFindByCode"]
    >
  >
>;
export type CustomerRuleControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomerRules>["customerRuleControllerFindOne"]
    >
  >
>;
export type CustomerRuleControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomerRules>["customerRuleControllerUpdate"]
    >
  >
>;
export type CustomerRuleControllerRemoveResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomerRules>["customerRuleControllerRemove"]
    >
  >
>;
export type CustomerRuleControllerInitializeDefaultRulesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getCustomerRules
      >["customerRuleControllerInitializeDefaultRules"]
    >
  >
>;
