/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { CreateDepartmentDto, UpdateDepartmentDto } from "../../models";

import { customInstance } from "../api-client";

export const getDepartments = () => {
  /**
   * @summary 创建部门
   */
  const departmentControllerCreate = (
    createDepartmentDto: CreateDepartmentDto,
  ) => {
    return customInstance<void>({
      url: `/departments`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createDepartmentDto,
    });
  };
  /**
   * @summary 获取部门树形结构
   */
  const departmentControllerFindTree = () => {
    return customInstance<void>({ url: `/departments`, method: "GET" });
  };
  /**
   * @summary 获取部门详情
   */
  const departmentControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/departments/${id}`, method: "GET" });
  };
  /**
   * @summary 更新部门
   */
  const departmentControllerUpdate = (
    id: string,
    updateDepartmentDto: UpdateDepartmentDto,
  ) => {
    return customInstance<void>({
      url: `/departments/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateDepartmentDto,
    });
  };
  /**
   * @summary 删除部门
   */
  const departmentControllerRemove = (id: string) => {
    return customInstance<void>({
      url: `/departments/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 获取部门下的用户列表
   */
  const departmentControllerFindUsers = (id: string) => {
    return customInstance<void>({
      url: `/departments/${id}/users`,
      method: "GET",
    });
  };
  return {
    departmentControllerCreate,
    departmentControllerFindTree,
    departmentControllerFindOne,
    departmentControllerUpdate,
    departmentControllerRemove,
    departmentControllerFindUsers,
  };
};
export type DepartmentControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDepartments>["departmentControllerCreate"]>
  >
>;
export type DepartmentControllerFindTreeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getDepartments>["departmentControllerFindTree"]
    >
  >
>;
export type DepartmentControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDepartments>["departmentControllerFindOne"]>
  >
>;
export type DepartmentControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDepartments>["departmentControllerUpdate"]>
  >
>;
export type DepartmentControllerRemoveResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDepartments>["departmentControllerRemove"]>
  >
>;
export type DepartmentControllerFindUsersResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getDepartments>["departmentControllerFindUsers"]
    >
  >
>;
