/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  EsignControllerFindAllParams,
  EsignControllerInitiateSigningBody,
} from "../../models";

import { customInstance } from "../api-client";

export const getEsign = () => {
  /**
   * @summary 初始化合同签署
   */
  const esignControllerInitiateSigning = (
    esignControllerInitiateSigningBody: EsignControllerInitiateSigningBody,
  ) => {
    const formData = new FormData();
    if (esignControllerInitiateSigningBody.file !== undefined) {
      formData.append(`file`, esignControllerInitiateSigningBody.file);
    }
    if (esignControllerInitiateSigningBody.contractId !== undefined) {
      formData.append(
        `contractId`,
        esignControllerInitiateSigningBody.contractId,
      );
    }
    if (esignControllerInitiateSigningBody.signers !== undefined) {
      esignControllerInitiateSigningBody.signers.forEach((value) =>
        formData.append(`signers`, JSON.stringify(value)),
      );
    }
    if (esignControllerInitiateSigningBody.subject !== undefined) {
      formData.append(`subject`, esignControllerInitiateSigningBody.subject);
    }
    if (esignControllerInitiateSigningBody.description !== undefined) {
      formData.append(
        `description`,
        esignControllerInitiateSigningBody.description,
      );
    }
    if (esignControllerInitiateSigningBody.remark !== undefined) {
      formData.append(`remark`, esignControllerInitiateSigningBody.remark);
    }

    return customInstance<void>({
      url: `/esign/initiate`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
    });
  };
  /**
   * @summary 获取签署状态
   */
  const esignControllerGetSigningStatus = (contractId: string) => {
    return customInstance<void>({
      url: `/esign/status/${contractId}`,
      method: "GET",
    });
  };
  /**
   * @summary 获取签署记录
   */
  const esignControllerGetRecord = (contractId: string) => {
    return customInstance<void>({
      url: `/esign/record/${contractId}`,
      method: "GET",
    });
  };
  /**
   * @summary 获取所有签署记录
   */
  const esignControllerFindAll = (params: EsignControllerFindAllParams) => {
    return customInstance<void>({
      url: `/esign/records`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 处理 e签宝回调通知
   */
  const esignControllerHandleCallback = () => {
    return customInstance<void>({ url: `/esign/callback`, method: "POST" });
  };
  return {
    esignControllerInitiateSigning,
    esignControllerGetSigningStatus,
    esignControllerGetRecord,
    esignControllerFindAll,
    esignControllerHandleCallback,
  };
};
export type EsignControllerInitiateSigningResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEsign>["esignControllerInitiateSigning"]>
  >
>;
export type EsignControllerGetSigningStatusResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEsign>["esignControllerGetSigningStatus"]>
  >
>;
export type EsignControllerGetRecordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEsign>["esignControllerGetRecord"]>>
>;
export type EsignControllerFindAllResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEsign>["esignControllerFindAll"]>>
>;
export type EsignControllerHandleCallbackResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEsign>["esignControllerHandleCallback"]>
  >
>;
