/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateFollowRecordDto,
  FollowRecordControllerFindAllParams,
  UpdateFollowRecordDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getFollowRecords = () => {
  /**
   * @summary 查询跟进记录列表
   */
  const followRecordControllerFindAll = (
    params: FollowRecordControllerFindAllParams,
  ) => {
    return customInstance<void>({
      url: `/follow-records`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 创建跟进记录
   */
  const followRecordControllerCreate = (
    createFollowRecordDto: CreateFollowRecordDto,
  ) => {
    return customInstance<void>({
      url: `/follow-records`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createFollowRecordDto,
    });
  };
  /**
   * @summary 获取跟进记录详情
   */
  const followRecordControllerFindOne = (id: string) => {
    return customInstance<void>({
      url: `/follow-records/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 更新跟进记录
   */
  const followRecordControllerUpdate = (
    id: string,
    updateFollowRecordDto: UpdateFollowRecordDto,
  ) => {
    return customInstance<void>({
      url: `/follow-records/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateFollowRecordDto,
    });
  };
  /**
   * @summary 删除跟进记录
   */
  const followRecordControllerRemove = (id: string) => {
    return customInstance<void>({
      url: `/follow-records/${id}`,
      method: "DELETE",
    });
  };
  return {
    followRecordControllerFindAll,
    followRecordControllerCreate,
    followRecordControllerFindOne,
    followRecordControllerUpdate,
    followRecordControllerRemove,
  };
};
export type FollowRecordControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getFollowRecords>["followRecordControllerFindAll"]
    >
  >
>;
export type FollowRecordControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getFollowRecords>["followRecordControllerCreate"]
    >
  >
>;
export type FollowRecordControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getFollowRecords>["followRecordControllerFindOne"]
    >
  >
>;
export type FollowRecordControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getFollowRecords>["followRecordControllerUpdate"]
    >
  >
>;
export type FollowRecordControllerRemoveResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getFollowRecords>["followRecordControllerRemove"]
    >
  >
>;
