/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import { customInstance } from "../api-client";

export const getHealth = () => {
  /**
   * @summary 健康检查
   */
  const healthControllerCheck = () => {
    return customInstance<void>({ url: `/health`, method: "GET" });
  };
  /**
   * @summary 简单心跳检查
   */
  const healthControllerPing = () => {
    return customInstance<void>({ url: `/health/ping`, method: "GET" });
  };
  return { healthControllerCheck, healthControllerPing };
};
export type HealthControllerCheckResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getHealth>["healthControllerCheck"]>>
>;
export type HealthControllerPingResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getHealth>["healthControllerPing"]>>
>;
