/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateInvoiceDto,
  InvoiceControllerFindAllParams,
  InvoiceControllerGetCustomerSummaryParams,
  UpdateInvoiceDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getInvoices = () => {
  /**
   * @summary 创建开票记录
   */
  const invoiceControllerCreate = (createInvoiceDto: CreateInvoiceDto) => {
    return customInstance<void>({
      url: `/invoices`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createInvoiceDto,
    });
  };
  /**
   * @summary 获取开票记录列表
   */
  const invoiceControllerFindAll = (
    params?: InvoiceControllerFindAllParams,
  ) => {
    return customInstance<void>({ url: `/invoices`, method: "GET", params });
  };
  /**
   * @summary 获取客户开票汇总
   */
  const invoiceControllerGetCustomerSummary = (
    customerId: string,
    params: InvoiceControllerGetCustomerSummaryParams,
  ) => {
    return customInstance<void>({
      url: `/invoices/customer/${customerId}/summary`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取开票记录详情
   */
  const invoiceControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/invoices/${id}`, method: "GET" });
  };
  /**
   * @summary 更新开票记录
   */
  const invoiceControllerUpdate = (
    id: string,
    updateInvoiceDto: UpdateInvoiceDto,
  ) => {
    return customInstance<void>({
      url: `/invoices/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateInvoiceDto,
    });
  };
  /**
   * @summary 删除开票记录
   */
  const invoiceControllerRemove = (id: string) => {
    return customInstance<void>({ url: `/invoices/${id}`, method: "DELETE" });
  };
  return {
    invoiceControllerCreate,
    invoiceControllerFindAll,
    invoiceControllerGetCustomerSummary,
    invoiceControllerFindOne,
    invoiceControllerUpdate,
    invoiceControllerRemove,
  };
};
export type InvoiceControllerCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getInvoices>["invoiceControllerCreate"]>>
>;
export type InvoiceControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getInvoices>["invoiceControllerFindAll"]>
  >
>;
export type InvoiceControllerGetCustomerSummaryResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getInvoices>["invoiceControllerGetCustomerSummary"]
    >
  >
>;
export type InvoiceControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getInvoices>["invoiceControllerFindOne"]>
  >
>;
export type InvoiceControllerUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getInvoices>["invoiceControllerUpdate"]>>
>;
export type InvoiceControllerRemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getInvoices>["invoiceControllerRemove"]>>
>;
