/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { LoginLogsControllerFindLoginLogsParams } from "../../models";

import { customInstance } from "../api-client";

export const getLoginLogs = () => {
  /**
   * @summary 分页查询登录日志
   */
  const loginLogsControllerFindLoginLogs = (
    params?: LoginLogsControllerFindLoginLogsParams,
  ) => {
    return customInstance<void>({ url: `/login-logs`, method: "GET", params });
  };
  /**
   * @summary 获取登录日志详情
   */
  const loginLogsControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/login-logs/${id}`, method: "GET" });
  };
  return { loginLogsControllerFindLoginLogs, loginLogsControllerFindOne };
};
export type LoginLogsControllerFindLoginLogsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getLoginLogs>["loginLogsControllerFindLoginLogs"]
    >
  >
>;
export type LoginLogsControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getLoginLogs>["loginLogsControllerFindOne"]>
  >
>;
