/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  ExportLogDto,
  LogsControllerFindOperationLogsParams,
  LogsControllerFindSystemLogsParams,
} from "../../models";

import { customInstance } from "../api-client";

export const getLogs = () => {
  /**
   * @summary 分页查询操作日志
   */
  const logsControllerFindOperationLogs = (
    params?: LogsControllerFindOperationLogsParams,
  ) => {
    return customInstance<void>({
      url: `/logs/operations`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 分页查询系统日志
   */
  const logsControllerFindSystemLogs = (
    params?: LogsControllerFindSystemLogsParams,
  ) => {
    return customInstance<void>({ url: `/logs/system`, method: "GET", params });
  };
  /**
   * @summary 获取日志详情
   */
  const logsControllerFindOne = (type: string, id: string) => {
    return customInstance<void>({ url: `/logs/${type}/${id}`, method: "GET" });
  };
  /**
   * @summary 导出日志为 CSV
   */
  const logsControllerExportToCsv = (exportLogDto: ExportLogDto) => {
    return customInstance<unknown>({
      url: `/logs/export`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: exportLogDto,
    });
  };
  return {
    logsControllerFindOperationLogs,
    logsControllerFindSystemLogs,
    logsControllerFindOne,
    logsControllerExportToCsv,
  };
};
export type LogsControllerFindOperationLogsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getLogs>["logsControllerFindOperationLogs"]>
  >
>;
export type LogsControllerFindSystemLogsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getLogs>["logsControllerFindSystemLogs"]>
  >
>;
export type LogsControllerFindOneResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLogs>["logsControllerFindOne"]>>
>;
export type LogsControllerExportToCsvResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLogs>["logsControllerExportToCsv"]>>
>;
