/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateMenuDto,
  InitializeResultResponse,
  MenuGroupDto,
  MenuItemDto,
  UpdateMenuDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getMenus = () => {
  /**
   * 根据用户角色过滤菜单，返回按 groupTitle 分组的菜单结构
   * @summary 获取当前用户的菜单树
   */
  const menuControllerGetUserMenus = () => {
    return customInstance<MenuGroupDto[]>({
      url: `/menus/user`,
      method: "GET",
    });
  };
  /**
   * 创建默认菜单结构和按钮权限，使用 upsert 模式可重复调用。
   * @summary 初始化菜单数据
   */
  const menuControllerInitializeMenus = () => {
    return customInstance<InitializeResultResponse>({
      url: `/menus/initialize`,
      method: "POST",
    });
  };
  /**
   * 返回所有启用的菜单和按钮，用于角色权限配置。返回树形结构，包含父子关系。
   * @summary 获取所有菜单（树形结构）
   */
  const menuControllerGetAllMenus = () => {
    return customInstance<MenuItemDto[]>({ url: `/menus/all`, method: "GET" });
  };
  /**
   * 创建新的菜单或按钮节点
   * @summary 创建菜单
   */
  const menuControllerCreateMenu = (createMenuDto: CreateMenuDto) => {
    return customInstance<MenuItemDto>({
      url: `/menus`,
      method: "POST",
      data: createMenuDto,
    });
  };
  /**
   * 更新指定菜单信息
   * @summary 更新菜单
   */
  const menuControllerUpdateMenu = (
    id: string,
    updateMenuDto: UpdateMenuDto,
  ) => {
    return customInstance<MenuItemDto>({
      url: `/menus/${id}`,
      method: "PATCH",
      data: updateMenuDto,
    });
  };
  /**
   * 删除指定菜单，如果有子菜单则无法删除
   * @summary 删除菜单
   */
  const menuControllerDeleteMenu = (id: string) => {
    return customInstance<void>({ url: `/menus/${id}`, method: "DELETE" });
  };
  return {
    menuControllerGetUserMenus,
    menuControllerInitializeMenus,
    menuControllerGetAllMenus,
    menuControllerCreateMenu,
    menuControllerUpdateMenu,
    menuControllerDeleteMenu,
  };
};
export type MenuControllerGetUserMenusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMenus>["menuControllerGetUserMenus"]>>
>;
export type MenuControllerInitializeMenusResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getMenus>["menuControllerInitializeMenus"]>
  >
>;
export type MenuControllerGetAllMenusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMenus>["menuControllerGetAllMenus"]>>
>;
export type MenuControllerCreateMenuResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMenus>["menuControllerCreateMenu"]>>
>;
export type MenuControllerUpdateMenuResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMenus>["menuControllerUpdateMenu"]>>
>;
export type MenuControllerDeleteMenuResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMenus>["menuControllerDeleteMenu"]>>
>;
