/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { NotificationControllerGetUserNotificationsParams } from "../../models";

import { customInstance } from "../api-client";

export const getNotifications = () => {
  /**
   * @summary 获取当前用户通知
   */
  const notificationControllerGetUserNotifications = (
    params: NotificationControllerGetUserNotificationsParams,
  ) => {
    return customInstance<void>({
      url: `/notifications`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取未读通知数量
   */
  const notificationControllerGetUnreadCount = (id: string) => {
    return customInstance<void>({
      url: `/notifications/${id}/unread-count`,
      method: "GET",
    });
  };
  /**
   * @summary 标记通知为已读
   */
  const notificationControllerMarkAsRead = (id: string) => {
    return customInstance<void>({
      url: `/notifications/${id}/read`,
      method: "POST",
    });
  };
  /**
   * @summary 标记所有通知为已读
   */
  const notificationControllerMarkAllAsRead = () => {
    return customInstance<void>({
      url: `/notifications/read-all`,
      method: "POST",
    });
  };
  /**
   * @summary 删除通知
   */
  const notificationControllerDeleteNotification = (id: string) => {
    return customInstance<void>({
      url: `/notifications/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 发送通知
   */
  const notificationControllerSendNotification = () => {
    return customInstance<void>({ url: `/notifications/send`, method: "POST" });
  };
  /**
   * @summary 测试Webhook发送
   */
  const notificationControllerTestWebhook = () => {
    return customInstance<void>({
      url: `/notifications/test-webhook`,
      method: "POST",
    });
  };
  return {
    notificationControllerGetUserNotifications,
    notificationControllerGetUnreadCount,
    notificationControllerMarkAsRead,
    notificationControllerMarkAllAsRead,
    notificationControllerDeleteNotification,
    notificationControllerSendNotification,
    notificationControllerTestWebhook,
  };
};
export type NotificationControllerGetUserNotificationsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getNotifications
      >["notificationControllerGetUserNotifications"]
    >
  >
>;
export type NotificationControllerGetUnreadCountResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getNotifications
      >["notificationControllerGetUnreadCount"]
    >
  >
>;
export type NotificationControllerMarkAsReadResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getNotifications>["notificationControllerMarkAsRead"]
    >
  >
>;
export type NotificationControllerMarkAllAsReadResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getNotifications>["notificationControllerMarkAllAsRead"]
    >
  >
>;
export type NotificationControllerDeleteNotificationResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getNotifications
      >["notificationControllerDeleteNotification"]
    >
  >
>;
export type NotificationControllerSendNotificationResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getNotifications
      >["notificationControllerSendNotification"]
    >
  >
>;
export type NotificationControllerTestWebhookResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getNotifications>["notificationControllerTestWebhook"]
    >
  >
>;
