/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  OssControllerFindFilesParams,
  UploadFileDto,
  UploadUrlDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getOss = () => {
  /**
   * @summary 上传文件
   */
  const ossControllerUploadFile = (uploadFileDto: UploadFileDto) => {
    return customInstance<void>({
      url: `/oss/upload`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: uploadFileDto,
    });
  };
  /**
   * @summary 获取上传授权 URL（前端直传）
   */
  const ossControllerGetUploadUrl = (uploadUrlDto: UploadUrlDto) => {
    return customInstance<void>({
      url: `/oss/upload-url`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: uploadUrlDto,
    });
  };
  /**
   * @summary 分页查询文件列表
   */
  const ossControllerFindFiles = (params: OssControllerFindFilesParams) => {
    return customInstance<void>({ url: `/oss/files`, method: "GET", params });
  };
  /**
   * @summary 获取存储空间使用统计
   */
  const ossControllerGetUsage = () => {
    return customInstance<void>({ url: `/oss/usage`, method: "GET" });
  };
  /**
   * @summary 获取文件详情
   */
  const ossControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/oss/files/${id}`, method: "GET" });
  };
  /**
   * @summary 删除文件
   */
  const ossControllerRemove = (id: string) => {
    return customInstance<void>({ url: `/oss/files/${id}`, method: "DELETE" });
  };
  /**
   * @summary 下载文件（代理）
   */
  const ossControllerDownloadFile = (id: string) => {
    return customInstance<void>({ url: `/oss/download/${id}`, method: "GET" });
  };
  return {
    ossControllerUploadFile,
    ossControllerGetUploadUrl,
    ossControllerFindFiles,
    ossControllerGetUsage,
    ossControllerFindOne,
    ossControllerRemove,
    ossControllerDownloadFile,
  };
};
export type OssControllerUploadFileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOss>["ossControllerUploadFile"]>>
>;
export type OssControllerGetUploadUrlResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOss>["ossControllerGetUploadUrl"]>>
>;
export type OssControllerFindFilesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOss>["ossControllerFindFiles"]>>
>;
export type OssControllerGetUsageResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOss>["ossControllerGetUsage"]>>
>;
export type OssControllerFindOneResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOss>["ossControllerFindOne"]>>
>;
export type OssControllerRemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOss>["ossControllerRemove"]>>
>;
export type OssControllerDownloadFileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getOss>["ossControllerDownloadFile"]>>
>;
