/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import { customInstance } from "../api-client";

export const getPaymentWebhooks = () => {
  /**
   * @summary 微信支付回调
   */
  const paymentWebhookControllerWechatCallback = () => {
    return customInstance<void>({ url: `/payment/wechat`, method: "POST" });
  };
  /**
   * @summary 支付宝支付回调
   */
  const paymentWebhookControllerAlipayCallback = () => {
    return customInstance<void>({ url: `/payment/alipay`, method: "POST" });
  };
  /**
   * @summary 查询支付订单的回调日志
   */
  const paymentWebhookControllerGetCallbackLogsByOrder = (id: string) => {
    return customInstance<void>({
      url: `/payment/orders/${id}/callback-logs`,
      method: "GET",
    });
  };
  /**
   * @summary 查询所有支付回调日志
   */
  const paymentWebhookControllerGetAllCallbackLogs = () => {
    return customInstance<void>({
      url: `/payment/callback-logs`,
      method: "GET",
    });
  };
  return {
    paymentWebhookControllerWechatCallback,
    paymentWebhookControllerAlipayCallback,
    paymentWebhookControllerGetCallbackLogsByOrder,
    paymentWebhookControllerGetAllCallbackLogs,
  };
};
export type PaymentWebhookControllerWechatCallbackResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPaymentWebhooks
      >["paymentWebhookControllerWechatCallback"]
    >
  >
>;
export type PaymentWebhookControllerAlipayCallbackResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPaymentWebhooks
      >["paymentWebhookControllerAlipayCallback"]
    >
  >
>;
export type PaymentWebhookControllerGetCallbackLogsByOrderResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPaymentWebhooks
      >["paymentWebhookControllerGetCallbackLogsByOrder"]
    >
  >
>;
export type PaymentWebhookControllerGetAllCallbackLogsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPaymentWebhooks
      >["paymentWebhookControllerGetAllCallbackLogs"]
    >
  >
>;
