/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { CertificateConfigDto, VerifyCertificateDto } from "../../models";

import { customInstance } from "../api-client";

export const getPaymentCertificates = () => {
  /**
   * @summary 保存证书文件
   */
  const certificateControllerSaveCertificate = (
    certificateConfigDto: CertificateConfigDto,
  ) => {
    return customInstance<void>({
      url: `/payment-certificates/save`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: certificateConfigDto,
    });
  };
  /**
   * @summary 验证证书配置
   */
  const certificateControllerVerifyCertificates = (
    verifyCertificateDto: VerifyCertificateDto,
  ) => {
    return customInstance<void>({
      url: `/payment-certificates/verify`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: verifyCertificateDto,
    });
  };
  /**
   * @summary 列出所有证书文件
   */
  const certificateControllerListCertificates = () => {
    return customInstance<void>({
      url: `/payment-certificates/list`,
      method: "GET",
    });
  };
  return {
    certificateControllerSaveCertificate,
    certificateControllerVerifyCertificates,
    certificateControllerListCertificates,
  };
};
export type CertificateControllerSaveCertificateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPaymentCertificates
      >["certificateControllerSaveCertificate"]
    >
  >
>;
export type CertificateControllerVerifyCertificatesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPaymentCertificates
      >["certificateControllerVerifyCertificates"]
    >
  >
>;
export type CertificateControllerListCertificatesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPaymentCertificates
      >["certificateControllerListCertificates"]
    >
  >
>;
