/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreatePaymentConfigDto,
  PaymentConfigControllerFindAllParams,
  UpdatePaymentConfigDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getPaymentConfigs = () => {
  /**
   * @summary 创建支付配置
   */
  const paymentConfigControllerCreate = (
    createPaymentConfigDto: CreatePaymentConfigDto,
  ) => {
    return customInstance<void>({
      url: `/payment/configs`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPaymentConfigDto,
    });
  };
  /**
   * @summary 获取支付配置列表
   */
  const paymentConfigControllerFindAll = (
    params?: PaymentConfigControllerFindAllParams,
  ) => {
    return customInstance<void>({
      url: `/payment/configs`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 更新支付配置
   */
  const paymentConfigControllerUpdate = (
    id: string,
    updatePaymentConfigDto: UpdatePaymentConfigDto,
  ) => {
    return customInstance<void>({
      url: `/payment/configs/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updatePaymentConfigDto,
    });
  };
  /**
   * @summary 删除支付配置
   */
  const paymentConfigControllerDelete = (id: string) => {
    return customInstance<void>({
      url: `/payment/configs/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 获取支付配置详情
   */
  const paymentConfigControllerFindOne = (id: string) => {
    return customInstance<void>({
      url: `/payment/configs/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 启用/禁用支付配置
   */
  const paymentConfigControllerToggle = (id: string) => {
    return customInstance<void>({
      url: `/payment/configs/${id}/toggle`,
      method: "PATCH",
    });
  };
  /**
   * @summary 获取激活的支付配置
   */
  const paymentConfigControllerGetActiveConfig = (
    paymentMethod: string,
    paymentChannel: string,
  ) => {
    return customInstance<void>({
      url: `/payment/configs/active/${paymentMethod}/${paymentChannel}`,
      method: "GET",
    });
  };
  return {
    paymentConfigControllerCreate,
    paymentConfigControllerFindAll,
    paymentConfigControllerUpdate,
    paymentConfigControllerDelete,
    paymentConfigControllerFindOne,
    paymentConfigControllerToggle,
    paymentConfigControllerGetActiveConfig,
  };
};
export type PaymentConfigControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentConfigs>["paymentConfigControllerCreate"]
    >
  >
>;
export type PaymentConfigControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentConfigs>["paymentConfigControllerFindAll"]
    >
  >
>;
export type PaymentConfigControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentConfigs>["paymentConfigControllerUpdate"]
    >
  >
>;
export type PaymentConfigControllerDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentConfigs>["paymentConfigControllerDelete"]
    >
  >
>;
export type PaymentConfigControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentConfigs>["paymentConfigControllerFindOne"]
    >
  >
>;
export type PaymentConfigControllerToggleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentConfigs>["paymentConfigControllerToggle"]
    >
  >
>;
export type PaymentConfigControllerGetActiveConfigResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPaymentConfigs
      >["paymentConfigControllerGetActiveConfig"]
    >
  >
>;
