/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreatePaymentDto,
  PaymentControllerFindAllParams,
  UpdatePaymentDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getPayments = () => {
  /**
   * @summary 创建收款记录
   */
  const paymentControllerCreate = (createPaymentDto: CreatePaymentDto) => {
    return customInstance<void>({
      url: `/payments`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPaymentDto,
    });
  };
  /**
   * @summary 获取收款记录列表
   */
  const paymentControllerFindAll = (
    params?: PaymentControllerFindAllParams,
  ) => {
    return customInstance<void>({ url: `/payments`, method: "GET", params });
  };
  /**
   * @summary 获取合同的收款记录
   */
  const paymentControllerGetContractPayments = (contractId: string) => {
    return customInstance<void>({
      url: `/payments/contract/${contractId}`,
      method: "GET",
    });
  };
  /**
   * @summary 获取收款记录详情
   */
  const paymentControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/payments/${id}`, method: "GET" });
  };
  /**
   * @summary 更新收款记录
   */
  const paymentControllerUpdate = (
    id: string,
    updatePaymentDto: UpdatePaymentDto,
  ) => {
    return customInstance<void>({
      url: `/payments/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updatePaymentDto,
    });
  };
  /**
   * @summary 删除收款记录
   */
  const paymentControllerRemove = (id: string) => {
    return customInstance<void>({ url: `/payments/${id}`, method: "DELETE" });
  };
  /**
   * @summary 确认收款
   */
  const paymentControllerConfirmPayment = (id: string) => {
    return customInstance<void>({
      url: `/payments/${id}/confirm`,
      method: "POST",
    });
  };
  return {
    paymentControllerCreate,
    paymentControllerFindAll,
    paymentControllerGetContractPayments,
    paymentControllerFindOne,
    paymentControllerUpdate,
    paymentControllerRemove,
    paymentControllerConfirmPayment,
  };
};
export type PaymentControllerCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPayments>["paymentControllerCreate"]>>
>;
export type PaymentControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPayments>["paymentControllerFindAll"]>
  >
>;
export type PaymentControllerGetContractPaymentsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPayments>["paymentControllerGetContractPayments"]
    >
  >
>;
export type PaymentControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPayments>["paymentControllerFindOne"]>
  >
>;
export type PaymentControllerUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPayments>["paymentControllerUpdate"]>>
>;
export type PaymentControllerRemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPayments>["paymentControllerRemove"]>>
>;
export type PaymentControllerConfirmPaymentResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPayments>["paymentControllerConfirmPayment"]
    >
  >
>;
