/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreatePaymentOrderDto,
  CreateQrCodeDto,
  PaymentOrderControllerFindAllParams,
  RefundDto,
  UpdatePaymentOrderDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getPaymentOrders = () => {
  /**
   * @summary 创建支付订单
   */
  const paymentOrderControllerCreate = (
    createPaymentOrderDto: CreatePaymentOrderDto,
  ) => {
    return customInstance<void>({
      url: `/payment/orders`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPaymentOrderDto,
    });
  };
  /**
   * @summary 获取支付订单列表
   */
  const paymentOrderControllerFindAll = (
    params?: PaymentOrderControllerFindAllParams,
  ) => {
    return customInstance<void>({
      url: `/payment/orders`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 更新支付订单
   */
  const paymentOrderControllerUpdate = (
    id: string,
    updatePaymentOrderDto: UpdatePaymentOrderDto,
  ) => {
    return customInstance<void>({
      url: `/payment/orders/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updatePaymentOrderDto,
    });
  };
  /**
   * @summary 删除支付订单
   */
  const paymentOrderControllerDelete = (id: string) => {
    return customInstance<void>({
      url: `/payment/orders/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 获取支付订单详情
   */
  const paymentOrderControllerFindOne = (id: string) => {
    return customInstance<void>({
      url: `/payment/orders/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 生成支付二维码
   */
  const paymentOrderControllerGenerateQrCode = (
    createQrCodeDto: CreateQrCodeDto,
  ) => {
    return customInstance<void>({
      url: `/payment/orders/qrcode`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createQrCodeDto,
    });
  };
  /**
   * @summary 申请退款
   */
  const paymentOrderControllerRefund = (refundDto: RefundDto) => {
    return customInstance<void>({
      url: `/payment/orders/refund`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: refundDto,
    });
  };
  /**
   * @summary 取消订单
   */
  const paymentOrderControllerCancelOrder = (id: string) => {
    return customInstance<void>({
      url: `/payment/orders/cancel/${id}`,
      method: "POST",
    });
  };
  /**
   * @summary 查询订单状态
   */
  const paymentOrderControllerCheckOrderStatus = (orderNo: string) => {
    return customInstance<void>({
      url: `/payment/orders/status/${orderNo}`,
      method: "GET",
    });
  };
  return {
    paymentOrderControllerCreate,
    paymentOrderControllerFindAll,
    paymentOrderControllerUpdate,
    paymentOrderControllerDelete,
    paymentOrderControllerFindOne,
    paymentOrderControllerGenerateQrCode,
    paymentOrderControllerRefund,
    paymentOrderControllerCancelOrder,
    paymentOrderControllerCheckOrderStatus,
  };
};
export type PaymentOrderControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentOrders>["paymentOrderControllerCreate"]
    >
  >
>;
export type PaymentOrderControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentOrders>["paymentOrderControllerFindAll"]
    >
  >
>;
export type PaymentOrderControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentOrders>["paymentOrderControllerUpdate"]
    >
  >
>;
export type PaymentOrderControllerDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentOrders>["paymentOrderControllerDelete"]
    >
  >
>;
export type PaymentOrderControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentOrders>["paymentOrderControllerFindOne"]
    >
  >
>;
export type PaymentOrderControllerGenerateQrCodeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPaymentOrders
      >["paymentOrderControllerGenerateQrCode"]
    >
  >
>;
export type PaymentOrderControllerRefundResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentOrders>["paymentOrderControllerRefund"]
    >
  >
>;
export type PaymentOrderControllerCancelOrderResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentOrders>["paymentOrderControllerCancelOrder"]
    >
  >
>;
export type PaymentOrderControllerCheckOrderStatusResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPaymentOrders
      >["paymentOrderControllerCheckOrderStatus"]
    >
  >
>;
