/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import { customInstance } from "../api-client";

export const getPaymentTest = () => {
  /**
   * @summary 测试支付(仅测试环境)
   */
  const paymentTestControllerTestPay = (orderNo: string) => {
    return customInstance<void>({
      url: `/payment-test/pay/${orderNo}`,
      method: "POST",
    });
  };
  /**
   * @summary 重置订单状态(仅测试环境)
   */
  const paymentTestControllerResetOrder = (orderNo: string) => {
    return customInstance<void>({
      url: `/payment-test/reset/${orderNo}`,
      method: "POST",
    });
  };
  return { paymentTestControllerTestPay, paymentTestControllerResetOrder };
};
export type PaymentTestControllerTestPayResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentTest>["paymentTestControllerTestPay"]
    >
  >
>;
export type PaymentTestControllerResetOrderResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPaymentTest>["paymentTestControllerResetOrder"]
    >
  >
>;
