/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CalculatePriceDto,
  CreatePricingRuleDto,
  PricingControllerFindAllRulesParams,
  UpdatePricingRuleDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getPricing = () => {
  /**
   * @summary 创建定价规则
   */
  const pricingControllerCreateRule = (
    createPricingRuleDto: CreatePricingRuleDto,
  ) => {
    return customInstance<void>({
      url: `/pricing/rules`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPricingRuleDto,
    });
  };
  /**
   * @summary 查询所有定价规则
   */
  const pricingControllerFindAllRules = (
    params: PricingControllerFindAllRulesParams,
  ) => {
    return customInstance<void>({
      url: `/pricing/rules`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 查询单个定价规则
   */
  const pricingControllerFindOneRule = (id: string) => {
    return customInstance<void>({ url: `/pricing/rules/${id}`, method: "GET" });
  };
  /**
   * @summary 更新定价规则
   */
  const pricingControllerUpdateRule = (
    id: string,
    updatePricingRuleDto: UpdatePricingRuleDto,
  ) => {
    return customInstance<void>({
      url: `/pricing/rules/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updatePricingRuleDto,
    });
  };
  /**
   * @summary 删除定价规则
   */
  const pricingControllerRemoveRule = (id: string) => {
    return customInstance<void>({
      url: `/pricing/rules/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 查询产品的定价规则
   */
  const pricingControllerFindByProduct = (productId: string) => {
    return customInstance<void>({
      url: `/pricing/products/${productId}/rules`,
      method: "GET",
    });
  };
  /**
   * @summary 计算服务价格
   */
  const pricingControllerCalculatePrice = (
    calculatePriceDto: CalculatePriceDto,
  ) => {
    return customInstance<void>({
      url: `/pricing/calculate`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: calculatePriceDto,
    });
  };
  return {
    pricingControllerCreateRule,
    pricingControllerFindAllRules,
    pricingControllerFindOneRule,
    pricingControllerUpdateRule,
    pricingControllerRemoveRule,
    pricingControllerFindByProduct,
    pricingControllerCalculatePrice,
  };
};
export type PricingControllerCreateRuleResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPricing>["pricingControllerCreateRule"]>
  >
>;
export type PricingControllerFindAllRulesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPricing>["pricingControllerFindAllRules"]>
  >
>;
export type PricingControllerFindOneRuleResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPricing>["pricingControllerFindOneRule"]>
  >
>;
export type PricingControllerUpdateRuleResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPricing>["pricingControllerUpdateRule"]>
  >
>;
export type PricingControllerRemoveRuleResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPricing>["pricingControllerRemoveRule"]>
  >
>;
export type PricingControllerFindByProductResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPricing>["pricingControllerFindByProduct"]>
  >
>;
export type PricingControllerCalculatePriceResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPricing>["pricingControllerCalculatePrice"]>
  >
>;
