/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateProductDto,
  ProductControllerFindAllParams,
  UpdateProductDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getProducts = () => {
  /**
   * @summary 创建产品
   */
  const productControllerCreate = (createProductDto: CreateProductDto) => {
    return customInstance<void>({
      url: `/products`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createProductDto,
    });
  };
  /**
   * @summary 获取产品列表
   */
  const productControllerFindAll = (
    params?: ProductControllerFindAllParams,
  ) => {
    return customInstance<void>({ url: `/products`, method: "GET", params });
  };
  /**
   * @summary 获取产品详情
   */
  const productControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/products/${id}`, method: "GET" });
  };
  /**
   * @summary 更新产品
   */
  const productControllerUpdate = (
    id: string,
    updateProductDto: UpdateProductDto,
  ) => {
    return customInstance<void>({
      url: `/products/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateProductDto,
    });
  };
  /**
   * @summary 删除产品
   */
  const productControllerRemove = (id: string) => {
    return customInstance<void>({ url: `/products/${id}`, method: "DELETE" });
  };
  return {
    productControllerCreate,
    productControllerFindAll,
    productControllerFindOne,
    productControllerUpdate,
    productControllerRemove,
  };
};
export type ProductControllerCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProducts>["productControllerCreate"]>>
>;
export type ProductControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProducts>["productControllerFindAll"]>
  >
>;
export type ProductControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProducts>["productControllerFindOne"]>
  >
>;
export type ProductControllerUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProducts>["productControllerUpdate"]>>
>;
export type ProductControllerRemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProducts>["productControllerRemove"]>>
>;
