/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { SubmitContactDto } from "../../models";

import { customInstance } from "../api-client";

export const getPublicContact = () => {
  /**
   * @summary 提交联系表单（公开接口）
   */
  const publicContactControllerSubmit = (
    submitContactDto: SubmitContactDto,
  ) => {
    return customInstance<void>({
      url: `/public/contact/submit`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: submitContactDto,
    });
  };
  return { publicContactControllerSubmit };
};
export type PublicContactControllerSubmitResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPublicContact>["publicContactControllerSubmit"]
    >
  >
>;
