/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import { customInstance } from "../api-client";

export const getPublicSystemConfig = () => {
  /**
   * @summary 获取公开配置（无需认证）
   */
  const systemPublicControllerFindPublic = () => {
    return customInstance<void>({
      url: `/public/system/config`,
      method: "GET",
    });
  };
  /**
   * @summary 获取登录页配置（无需认证）
   */
  const systemPublicControllerGetLoginConfig = () => {
    return customInstance<void>({
      url: `/public/system/login-config`,
      method: "GET",
    });
  };
  return {
    systemPublicControllerFindPublic,
    systemPublicControllerGetLoginConfig,
  };
};
export type SystemPublicControllerFindPublicResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPublicSystemConfig
      >["systemPublicControllerFindPublic"]
    >
  >
>;
export type SystemPublicControllerGetLoginConfigResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPublicSystemConfig
      >["systemPublicControllerGetLoginConfig"]
    >
  >
>;
