/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { ProductPublicControllerFindPublishedProductsParams } from "../../models";

import { customInstance } from "../api-client";

export const getPublicProducts = () => {
  /**
   * @summary Get published products list
   */
  const productPublicControllerFindPublishedProducts = (
    params?: ProductPublicControllerFindPublishedProductsParams,
  ) => {
    return customInstance<void>({
      url: `/public/products`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary Get product by code
   */
  const productPublicControllerFindByCode = (code: string) => {
    return customInstance<void>({
      url: `/public/products/${code}`,
      method: "GET",
    });
  };
  return {
    productPublicControllerFindPublishedProducts,
    productPublicControllerFindByCode,
  };
};
export type ProductPublicControllerFindPublishedProductsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPublicProducts
      >["productPublicControllerFindPublishedProducts"]
    >
  >
>;
export type ProductPublicControllerFindByCodeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPublicProducts>["productPublicControllerFindByCode"]
    >
  >
>;
