/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CmsPublicControllerFindPublishedContentsParams,
  CmsPublicControllerGetPageElementsParams,
  CmsPublicControllerGetPublishedArticlesParams,
  CmsPublicControllerGetPublishedCasesParams,
  CmsPublicControllerGetPublishedProfilesParams,
  CmsPublicControllerGetPublishedShowcasesParams,
} from "../../models";

import { customInstance } from "../api-client";

export const getPublicCms = () => {
  /**
   * @summary Get published content list
   */
  const cmsPublicControllerFindPublishedContents = (
    params?: CmsPublicControllerFindPublishedContentsParams,
  ) => {
    return customInstance<void>({
      url: `/public/cms/contents`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary Get content by slug
   */
  const cmsPublicControllerFindContentBySlug = (slug: string) => {
    return customInstance<void>({
      url: `/public/cms/contents/${slug}`,
      method: "GET",
    });
  };
  /**
   * @summary Get published articles
   */
  const cmsPublicControllerGetPublishedArticles = (
    params?: CmsPublicControllerGetPublishedArticlesParams,
  ) => {
    return customInstance<void>({
      url: `/public/cms/articles`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary Get published case studies
   */
  const cmsPublicControllerGetPublishedCases = (
    params?: CmsPublicControllerGetPublishedCasesParams,
  ) => {
    return customInstance<void>({
      url: `/public/cms/cases`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary Get published product showcases
   */
  const cmsPublicControllerGetPublishedShowcases = (
    params?: CmsPublicControllerGetPublishedShowcasesParams,
  ) => {
    return customInstance<void>({
      url: `/public/cms/product-showcases`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary Get published user profiles
   */
  const cmsPublicControllerGetPublishedProfiles = (
    params?: CmsPublicControllerGetPublishedProfilesParams,
  ) => {
    return customInstance<void>({
      url: `/public/cms/profiles`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary Get published page elements
   */
  const cmsPublicControllerGetPageElements = (
    params?: CmsPublicControllerGetPageElementsParams,
  ) => {
    return customInstance<void>({
      url: `/public/cms/page-elements`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary Get page element by slug
   */
  const cmsPublicControllerGetPageElementBySlug = (slug: string) => {
    return customInstance<void>({
      url: `/public/cms/page-elements/${slug}`,
      method: "GET",
    });
  };
  /**
   * @summary Get published page by slug
   */
  const cmsPublicControllerFindPageBySlug = (slug: string) => {
    return customInstance<void>({
      url: `/public/cms/pages/${slug}`,
      method: "GET",
    });
  };
  /**
   * @summary Get all tags
   */
  const cmsPublicControllerFindAllTags = () => {
    return customInstance<void>({ url: `/public/cms/tags`, method: "GET" });
  };
  /**
   * @summary Get content preview by token
   */
  const cmsPublicControllerGetContentPreview = (token: string) => {
    return customInstance<void>({
      url: `/public/cms/preview/contents/${token}`,
      method: "GET",
    });
  };
  /**
   * @summary Get page preview by token
   */
  const cmsPublicControllerGetPagePreview = (token: string) => {
    return customInstance<void>({
      url: `/public/cms/preview/pages/${token}`,
      method: "GET",
    });
  };
  return {
    cmsPublicControllerFindPublishedContents,
    cmsPublicControllerFindContentBySlug,
    cmsPublicControllerGetPublishedArticles,
    cmsPublicControllerGetPublishedCases,
    cmsPublicControllerGetPublishedShowcases,
    cmsPublicControllerGetPublishedProfiles,
    cmsPublicControllerGetPageElements,
    cmsPublicControllerGetPageElementBySlug,
    cmsPublicControllerFindPageBySlug,
    cmsPublicControllerFindAllTags,
    cmsPublicControllerGetContentPreview,
    cmsPublicControllerGetPagePreview,
  };
};
export type CmsPublicControllerFindPublishedContentsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPublicCms
      >["cmsPublicControllerFindPublishedContents"]
    >
  >
>;
export type CmsPublicControllerFindContentBySlugResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPublicCms>["cmsPublicControllerFindContentBySlug"]
    >
  >
>;
export type CmsPublicControllerGetPublishedArticlesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPublicCms>["cmsPublicControllerGetPublishedArticles"]
    >
  >
>;
export type CmsPublicControllerGetPublishedCasesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPublicCms>["cmsPublicControllerGetPublishedCases"]
    >
  >
>;
export type CmsPublicControllerGetPublishedShowcasesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPublicCms
      >["cmsPublicControllerGetPublishedShowcases"]
    >
  >
>;
export type CmsPublicControllerGetPublishedProfilesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPublicCms>["cmsPublicControllerGetPublishedProfiles"]
    >
  >
>;
export type CmsPublicControllerGetPageElementsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPublicCms>["cmsPublicControllerGetPageElements"]
    >
  >
>;
export type CmsPublicControllerGetPageElementBySlugResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPublicCms>["cmsPublicControllerGetPageElementBySlug"]
    >
  >
>;
export type CmsPublicControllerFindPageBySlugResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPublicCms>["cmsPublicControllerFindPageBySlug"]
    >
  >
>;
export type CmsPublicControllerFindAllTagsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPublicCms>["cmsPublicControllerFindAllTags"]
    >
  >
>;
export type CmsPublicControllerGetContentPreviewResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPublicCms>["cmsPublicControllerGetContentPreview"]
    >
  >
>;
export type CmsPublicControllerGetPagePreviewResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPublicCms>["cmsPublicControllerGetPagePreview"]
    >
  >
>;
