/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { CreateRoleDto, UpdateRoleDto } from "../../models";

import { customInstance } from "../api-client";

export const getRoles = () => {
  /**
   * @summary 创建角色
   */
  const rolesControllerCreateRole = (createRoleDto: CreateRoleDto) => {
    return customInstance<void>({
      url: `/roles`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createRoleDto,
    });
  };
  /**
   * @summary 查询所有角色
   */
  const rolesControllerFindAllRoles = () => {
    return customInstance<void>({ url: `/roles`, method: "GET" });
  };
  /**
   * @summary 查询单个角色
   */
  const rolesControllerFindOneRole = (id: string) => {
    return customInstance<void>({ url: `/roles/${id}`, method: "GET" });
  };
  /**
   * @summary 更新角色
   */
  const rolesControllerUpdateRole = (
    id: string,
    updateRoleDto: UpdateRoleDto,
  ) => {
    return customInstance<void>({
      url: `/roles/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateRoleDto,
    });
  };
  /**
   * @summary 删除角色
   */
  const rolesControllerRemoveRole = (id: string) => {
    return customInstance<void>({ url: `/roles/${id}`, method: "DELETE" });
  };
  /**
   * @summary 获取角色的菜单列表
   */
  const rolesControllerGetRoleMenus = (id: string) => {
    return customInstance<void>({ url: `/roles/${id}/menus`, method: "GET" });
  };
  /**
   * @summary 为角色分配菜单
   */
  const rolesControllerAssignMenusToRole = (id: string) => {
    return customInstance<void>({ url: `/roles/${id}/menus`, method: "PUT" });
  };
  return {
    rolesControllerCreateRole,
    rolesControllerFindAllRoles,
    rolesControllerFindOneRole,
    rolesControllerUpdateRole,
    rolesControllerRemoveRole,
    rolesControllerGetRoleMenus,
    rolesControllerAssignMenusToRole,
  };
};
export type RolesControllerCreateRoleResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>["rolesControllerCreateRole"]>>
>;
export type RolesControllerFindAllRolesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRoles>["rolesControllerFindAllRoles"]>
  >
>;
export type RolesControllerFindOneRoleResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>["rolesControllerFindOneRole"]>>
>;
export type RolesControllerUpdateRoleResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>["rolesControllerUpdateRole"]>>
>;
export type RolesControllerRemoveRoleResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>["rolesControllerRemoveRole"]>>
>;
export type RolesControllerGetRoleMenusResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRoles>["rolesControllerGetRoleMenus"]>
  >
>;
export type RolesControllerAssignMenusToRoleResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRoles>["rolesControllerAssignMenusToRole"]>
  >
>;
