/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateServiceTeamDto,
  ServiceTeamControllerFindAllParams,
  UpdateServiceTeamDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getServiceTeams = () => {
  /**
   * @summary 添加服务团队成员
   */
  const serviceTeamControllerCreate = (
    createServiceTeamDto: CreateServiceTeamDto,
  ) => {
    return customInstance<void>({
      url: `/service-teams`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createServiceTeamDto,
    });
  };
  /**
   * @summary 获取服务团队列表
   */
  const serviceTeamControllerFindAll = (
    params: ServiceTeamControllerFindAllParams,
  ) => {
    return customInstance<void>({
      url: `/service-teams`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取客户的服务团队(按角色分组)
   */
  const serviceTeamControllerGetCustomerTeamGrouped = (customerId: string) => {
    return customInstance<void>({
      url: `/service-teams/customer/${customerId}/grouped`,
      method: "GET",
    });
  };
  /**
   * @summary 获取服务团队成员详情
   */
  const serviceTeamControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/service-teams/${id}`, method: "GET" });
  };
  /**
   * @summary 更新服务团队成员
   */
  const serviceTeamControllerUpdate = (
    id: string,
    updateServiceTeamDto: UpdateServiceTeamDto,
  ) => {
    return customInstance<void>({
      url: `/service-teams/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateServiceTeamDto,
    });
  };
  /**
   * @summary 删除服务团队成员
   */
  const serviceTeamControllerRemove = (id: string) => {
    return customInstance<void>({
      url: `/service-teams/${id}`,
      method: "DELETE",
    });
  };
  return {
    serviceTeamControllerCreate,
    serviceTeamControllerFindAll,
    serviceTeamControllerGetCustomerTeamGrouped,
    serviceTeamControllerFindOne,
    serviceTeamControllerUpdate,
    serviceTeamControllerRemove,
  };
};
export type ServiceTeamControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getServiceTeams>["serviceTeamControllerCreate"]
    >
  >
>;
export type ServiceTeamControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getServiceTeams>["serviceTeamControllerFindAll"]
    >
  >
>;
export type ServiceTeamControllerGetCustomerTeamGroupedResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getServiceTeams
      >["serviceTeamControllerGetCustomerTeamGrouped"]
    >
  >
>;
export type ServiceTeamControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getServiceTeams>["serviceTeamControllerFindOne"]
    >
  >
>;
export type ServiceTeamControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getServiceTeams>["serviceTeamControllerUpdate"]
    >
  >
>;
export type ServiceTeamControllerRemoveResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getServiceTeams>["serviceTeamControllerRemove"]
    >
  >
>;
