/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  BatchPublishDto,
  CreateSocialMediaPostDto,
  PublishSocialMediaPostDto,
  SchedulePublishDto,
  SocialMediaPostControllerFindAllParams,
  UpdateSocialMediaPostDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getSocialMediaPosts = () => {
  /**
   * @summary 创建新媒体内容
   */
  const socialMediaPostControllerCreate = (
    createSocialMediaPostDto: CreateSocialMediaPostDto,
  ) => {
    return customInstance<void>({
      url: `/social-media/posts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createSocialMediaPostDto,
    });
  };
  /**
   * @summary 获取新媒体内容列表
   */
  const socialMediaPostControllerFindAll = (
    params?: SocialMediaPostControllerFindAllParams,
  ) => {
    return customInstance<void>({
      url: `/social-media/posts`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 更新新媒体内容
   */
  const socialMediaPostControllerUpdate = (
    id: string,
    updateSocialMediaPostDto: UpdateSocialMediaPostDto,
  ) => {
    return customInstance<void>({
      url: `/social-media/posts/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateSocialMediaPostDto,
    });
  };
  /**
   * @summary 删除新媒体内容
   */
  const socialMediaPostControllerDelete = (id: string) => {
    return customInstance<void>({
      url: `/social-media/posts/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 获取新媒体内容详情
   */
  const socialMediaPostControllerFindOne = (id: string) => {
    return customInstance<void>({
      url: `/social-media/posts/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 发布内容
   */
  const socialMediaPostControllerPublish = (
    publishSocialMediaPostDto: PublishSocialMediaPostDto,
  ) => {
    return customInstance<void>({
      url: `/social-media/posts/publish`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: publishSocialMediaPostDto,
    });
  };
  /**
   * @summary 定时发布
   */
  const socialMediaPostControllerSchedulePublish = (
    schedulePublishDto: SchedulePublishDto,
  ) => {
    return customInstance<void>({
      url: `/social-media/posts/schedule`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: schedulePublishDto,
    });
  };
  /**
   * @summary 取消定时发布
   */
  const socialMediaPostControllerCancelScheduled = (id: string) => {
    return customInstance<void>({
      url: `/social-media/posts/cancel-schedule/${id}`,
      method: "POST",
    });
  };
  /**
   * @summary 批量发布
   */
  const socialMediaPostControllerBatchPublish = (
    batchPublishDto: BatchPublishDto,
  ) => {
    return customInstance<void>({
      url: `/social-media/posts/batch-publish`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchPublishDto,
    });
  };
  /**
   * @summary 查询内容发布日志
   */
  const socialMediaPostControllerGetPublishLogs = (id: string) => {
    return customInstance<void>({
      url: `/social-media/posts/${id}/publish-logs`,
      method: "GET",
    });
  };
  /**
   * @summary 查询所有发布日志
   */
  const socialMediaPostControllerGetAllPublishLogs = () => {
    return customInstance<void>({
      url: `/social-media/posts/publish-logs`,
      method: "GET",
    });
  };
  return {
    socialMediaPostControllerCreate,
    socialMediaPostControllerFindAll,
    socialMediaPostControllerUpdate,
    socialMediaPostControllerDelete,
    socialMediaPostControllerFindOne,
    socialMediaPostControllerPublish,
    socialMediaPostControllerSchedulePublish,
    socialMediaPostControllerCancelScheduled,
    socialMediaPostControllerBatchPublish,
    socialMediaPostControllerGetPublishLogs,
    socialMediaPostControllerGetAllPublishLogs,
  };
};
export type SocialMediaPostControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSocialMediaPosts>["socialMediaPostControllerCreate"]
    >
  >
>;
export type SocialMediaPostControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSocialMediaPosts>["socialMediaPostControllerFindAll"]
    >
  >
>;
export type SocialMediaPostControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSocialMediaPosts>["socialMediaPostControllerUpdate"]
    >
  >
>;
export type SocialMediaPostControllerDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSocialMediaPosts>["socialMediaPostControllerDelete"]
    >
  >
>;
export type SocialMediaPostControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSocialMediaPosts>["socialMediaPostControllerFindOne"]
    >
  >
>;
export type SocialMediaPostControllerPublishResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSocialMediaPosts>["socialMediaPostControllerPublish"]
    >
  >
>;
export type SocialMediaPostControllerSchedulePublishResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSocialMediaPosts
      >["socialMediaPostControllerSchedulePublish"]
    >
  >
>;
export type SocialMediaPostControllerCancelScheduledResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSocialMediaPosts
      >["socialMediaPostControllerCancelScheduled"]
    >
  >
>;
export type SocialMediaPostControllerBatchPublishResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSocialMediaPosts
      >["socialMediaPostControllerBatchPublish"]
    >
  >
>;
export type SocialMediaPostControllerGetPublishLogsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSocialMediaPosts
      >["socialMediaPostControllerGetPublishLogs"]
    >
  >
>;
export type SocialMediaPostControllerGetAllPublishLogsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSocialMediaPosts
      >["socialMediaPostControllerGetAllPublishLogs"]
    >
  >
>;
