/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateSocialMediaAccountDto,
  RefreshTokenDto,
  SocialMediaAccountControllerFindAllParams,
  UpdateSocialMediaAccountDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getSocialMediaAccounts = () => {
  /**
   * @summary 创建新媒体账号
   */
  const socialMediaAccountControllerCreate = (
    createSocialMediaAccountDto: CreateSocialMediaAccountDto,
  ) => {
    return customInstance<void>({
      url: `/social-media/accounts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createSocialMediaAccountDto,
    });
  };
  /**
   * @summary 获取新媒体账号列表
   */
  const socialMediaAccountControllerFindAll = (
    params?: SocialMediaAccountControllerFindAllParams,
  ) => {
    return customInstance<void>({
      url: `/social-media/accounts`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 更新新媒体账号
   */
  const socialMediaAccountControllerUpdate = (
    id: string,
    updateSocialMediaAccountDto: UpdateSocialMediaAccountDto,
  ) => {
    return customInstance<void>({
      url: `/social-media/accounts/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateSocialMediaAccountDto,
    });
  };
  /**
   * @summary 删除新媒体账号
   */
  const socialMediaAccountControllerDelete = (id: string) => {
    return customInstance<void>({
      url: `/social-media/accounts/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 获取新媒体账号详情
   */
  const socialMediaAccountControllerFindOne = (id: string) => {
    return customInstance<void>({
      url: `/social-media/accounts/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 刷新访问令牌
   */
  const socialMediaAccountControllerRefreshToken = (
    refreshTokenDto: RefreshTokenDto,
  ) => {
    return customInstance<void>({
      url: `/social-media/accounts/refresh-token`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: refreshTokenDto,
    });
  };
  /**
   * @summary 验证账号有效性
   */
  const socialMediaAccountControllerValidateAccount = (id: string) => {
    return customInstance<void>({
      url: `/social-media/accounts/${id}/validate`,
      method: "GET",
    });
  };
  return {
    socialMediaAccountControllerCreate,
    socialMediaAccountControllerFindAll,
    socialMediaAccountControllerUpdate,
    socialMediaAccountControllerDelete,
    socialMediaAccountControllerFindOne,
    socialMediaAccountControllerRefreshToken,
    socialMediaAccountControllerValidateAccount,
  };
};
export type SocialMediaAccountControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSocialMediaAccounts
      >["socialMediaAccountControllerCreate"]
    >
  >
>;
export type SocialMediaAccountControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSocialMediaAccounts
      >["socialMediaAccountControllerFindAll"]
    >
  >
>;
export type SocialMediaAccountControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSocialMediaAccounts
      >["socialMediaAccountControllerUpdate"]
    >
  >
>;
export type SocialMediaAccountControllerDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSocialMediaAccounts
      >["socialMediaAccountControllerDelete"]
    >
  >
>;
export type SocialMediaAccountControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSocialMediaAccounts
      >["socialMediaAccountControllerFindOne"]
    >
  >
>;
export type SocialMediaAccountControllerRefreshTokenResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSocialMediaAccounts
      >["socialMediaAccountControllerRefreshToken"]
    >
  >
>;
export type SocialMediaAccountControllerValidateAccountResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSocialMediaAccounts
      >["socialMediaAccountControllerValidateAccount"]
    >
  >
>;
