/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  DashboardStatsDto,
  StatisticsControllerExportDataParams,
  StatisticsControllerGetContractRenewalStatsParams,
  StatisticsControllerGetCustomerGrowthTrendParams,
  StatisticsControllerGetInvoiceAnalysisParams,
  StatisticsControllerGetProductSalesStatsParams,
  StatisticsControllerGetSalesPerformanceParams,
} from "../../models";

import { customInstance } from "../api-client";

export const getStatistics = () => {
  /**
   * @summary 获取首页仪表板数据
   */
  const statisticsControllerGetDashboardStats = () => {
    return customInstance<DashboardStatsDto>({
      url: `/statistics/dashboard`,
      method: "GET",
    });
  };
  /**
   * @summary 获取客户增长趋势
   */
  const statisticsControllerGetCustomerGrowthTrend = (
    params?: StatisticsControllerGetCustomerGrowthTrendParams,
  ) => {
    return customInstance<void>({
      url: `/statistics/customer-growth`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取合同续约率统计
   */
  const statisticsControllerGetContractRenewalStats = (
    params?: StatisticsControllerGetContractRenewalStatsParams,
  ) => {
    return customInstance<void>({
      url: `/statistics/contract-renewal`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取开票金额分析
   */
  const statisticsControllerGetInvoiceAnalysis = (
    params?: StatisticsControllerGetInvoiceAnalysisParams,
  ) => {
    return customInstance<void>({
      url: `/statistics/invoice-analysis`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取销售业绩排行
   */
  const statisticsControllerGetSalesPerformance = (
    params?: StatisticsControllerGetSalesPerformanceParams,
  ) => {
    return customInstance<void>({
      url: `/statistics/sales-performance`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取产品销售统计
   */
  const statisticsControllerGetProductSalesStats = (
    params?: StatisticsControllerGetProductSalesStatsParams,
  ) => {
    return customInstance<void>({
      url: `/statistics/product-sales`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 导出数据
   */
  const statisticsControllerExportData = (
    params: StatisticsControllerExportDataParams,
  ) => {
    return customInstance<void>({
      url: `/statistics/export`,
      method: "GET",
      params,
    });
  };
  return {
    statisticsControllerGetDashboardStats,
    statisticsControllerGetCustomerGrowthTrend,
    statisticsControllerGetContractRenewalStats,
    statisticsControllerGetInvoiceAnalysis,
    statisticsControllerGetSalesPerformance,
    statisticsControllerGetProductSalesStats,
    statisticsControllerExportData,
  };
};
export type StatisticsControllerGetDashboardStatsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getStatistics>["statisticsControllerGetDashboardStats"]
    >
  >
>;
export type StatisticsControllerGetCustomerGrowthTrendResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getStatistics
      >["statisticsControllerGetCustomerGrowthTrend"]
    >
  >
>;
export type StatisticsControllerGetContractRenewalStatsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getStatistics
      >["statisticsControllerGetContractRenewalStats"]
    >
  >
>;
export type StatisticsControllerGetInvoiceAnalysisResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getStatistics>["statisticsControllerGetInvoiceAnalysis"]
    >
  >
>;
export type StatisticsControllerGetSalesPerformanceResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getStatistics
      >["statisticsControllerGetSalesPerformance"]
    >
  >
>;
export type StatisticsControllerGetProductSalesStatsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getStatistics
      >["statisticsControllerGetProductSalesStats"]
    >
  >
>;
export type StatisticsControllerExportDataResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getStatistics>["statisticsControllerExportData"]
    >
  >
>;
