/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { SystemLogsControllerGetLogsParams } from "../../models";

import { customInstance } from "../api-client";

export const getSystemLogs = () => {
  /**
   * @summary 获取系统日志 (PM2/Nginx/Redis)
   */
  const systemLogsControllerGetLogs = (
    type: "pm2" | "nginx" | "redis",
    params?: SystemLogsControllerGetLogsParams,
  ) => {
    return customInstance<void>({
      url: `/system-logs/${type}`,
      method: "GET",
      params,
    });
  };
  return { systemLogsControllerGetLogs };
};
export type SystemLogsControllerGetLogsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSystemLogs>["systemLogsControllerGetLogs"]>
  >
>;
