/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  SystemControllerFindCommonPhrasesParams,
  SystemControllerFindPaymentAccountsParams,
  SystemControllerSearchCommonPhrasesParams,
  SystemControllerSetDefaultPaymentAccountParams,
} from "../../models";

import { customInstance } from "../api-client";

export const getSystem = () => {
  /**
   * @summary 获取常用语列表
   */
  const systemControllerFindCommonPhrases = (
    params: SystemControllerFindCommonPhrasesParams,
  ) => {
    return customInstance<void>({
      url: `/system/common-phrases`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 创建常用语
   */
  const systemControllerCreateCommonPhrase = () => {
    return customInstance<void>({
      url: `/system/common-phrases`,
      method: "POST",
    });
  };
  /**
   * @summary 更新常用语
   */
  const systemControllerUpdateCommonPhrase = (id: string) => {
    return customInstance<void>({
      url: `/system/common-phrases/${id}`,
      method: "PATCH",
    });
  };
  /**
   * @summary 删除常用语
   */
  const systemControllerRemoveCommonPhrase = (id: string) => {
    return customInstance<void>({
      url: `/system/common-phrases/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 搜索常用语
   */
  const systemControllerSearchCommonPhrases = (
    params: SystemControllerSearchCommonPhrasesParams,
  ) => {
    return customInstance<void>({
      url: `/system/common-phrases/search`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 增加常用语使用次数
   */
  const systemControllerIncrementPhraseUsage = (id: string) => {
    return customInstance<void>({
      url: `/system/common-phrases/${id}/use`,
      method: "POST",
    });
  };
  /**
   * @summary 获取收款账号列表
   */
  const systemControllerFindPaymentAccounts = (
    params: SystemControllerFindPaymentAccountsParams,
  ) => {
    return customInstance<void>({
      url: `/system/payment-accounts`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 创建收款账号
   */
  const systemControllerCreatePaymentAccount = () => {
    return customInstance<void>({
      url: `/system/payment-accounts`,
      method: "POST",
    });
  };
  /**
   * @summary 获取默认收款账号
   */
  const systemControllerFindDefaultPaymentAccount = () => {
    return customInstance<void>({
      url: `/system/payment-accounts/default`,
      method: "GET",
    });
  };
  /**
   * @summary 更新收款账号
   */
  const systemControllerUpdatePaymentAccount = (id: string) => {
    return customInstance<void>({
      url: `/system/payment-accounts/${id}`,
      method: "PATCH",
    });
  };
  /**
   * @summary 删除收款账号
   */
  const systemControllerRemovePaymentAccount = (id: string) => {
    return customInstance<void>({
      url: `/system/payment-accounts/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 设置默认账号
   */
  const systemControllerSetDefaultPaymentAccount = (
    id: string,
    params: SystemControllerSetDefaultPaymentAccountParams,
  ) => {
    return customInstance<void>({
      url: `/system/payment-accounts/${id}/default`,
      method: "PATCH",
      params,
    });
  };
  return {
    systemControllerFindCommonPhrases,
    systemControllerCreateCommonPhrase,
    systemControllerUpdateCommonPhrase,
    systemControllerRemoveCommonPhrase,
    systemControllerSearchCommonPhrases,
    systemControllerIncrementPhraseUsage,
    systemControllerFindPaymentAccounts,
    systemControllerCreatePaymentAccount,
    systemControllerFindDefaultPaymentAccount,
    systemControllerUpdatePaymentAccount,
    systemControllerRemovePaymentAccount,
    systemControllerSetDefaultPaymentAccount,
  };
};
export type SystemControllerFindCommonPhrasesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSystem>["systemControllerFindCommonPhrases"]
    >
  >
>;
export type SystemControllerCreateCommonPhraseResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSystem>["systemControllerCreateCommonPhrase"]
    >
  >
>;
export type SystemControllerUpdateCommonPhraseResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSystem>["systemControllerUpdateCommonPhrase"]
    >
  >
>;
export type SystemControllerRemoveCommonPhraseResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSystem>["systemControllerRemoveCommonPhrase"]
    >
  >
>;
export type SystemControllerSearchCommonPhrasesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSystem>["systemControllerSearchCommonPhrases"]
    >
  >
>;
export type SystemControllerIncrementPhraseUsageResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSystem>["systemControllerIncrementPhraseUsage"]
    >
  >
>;
export type SystemControllerFindPaymentAccountsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSystem>["systemControllerFindPaymentAccounts"]
    >
  >
>;
export type SystemControllerCreatePaymentAccountResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSystem>["systemControllerCreatePaymentAccount"]
    >
  >
>;
export type SystemControllerFindDefaultPaymentAccountResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSystem>["systemControllerFindDefaultPaymentAccount"]
    >
  >
>;
export type SystemControllerUpdatePaymentAccountResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSystem>["systemControllerUpdatePaymentAccount"]
    >
  >
>;
export type SystemControllerRemovePaymentAccountResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSystem>["systemControllerRemovePaymentAccount"]
    >
  >
>;
export type SystemControllerSetDefaultPaymentAccountResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSystem>["systemControllerSetDefaultPaymentAccount"]
    >
  >
>;
