/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  BackupCodesDto,
  Disable2faDto,
  Enable2faDto,
  Setup2faResponseDto,
  TwoFactorStatusDto,
  VerifyTotpDto,
  VerifyTotpResponseDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getTwoFactor = () => {
  /**
   * @summary 生成 2FA 设置信息
   */
  const twoFactorControllerSetup = () => {
    return customInstance<Setup2faResponseDto>({
      url: `/two-factor/setup`,
      method: "POST",
    });
  };
  /**
   * @summary 启用 2FA
   */
  const twoFactorControllerEnable = (enable2faDto: Enable2faDto) => {
    return customInstance<BackupCodesDto>({
      url: `/two-factor/enable`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: enable2faDto,
    });
  };
  /**
   * @summary 禁用 2FA
   */
  const twoFactorControllerDisable = (disable2faDto: Disable2faDto) => {
    return customInstance<void>({
      url: `/two-factor/disable`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: disable2faDto,
    });
  };
  /**
   * @summary 验证 TOTP 验证码
   */
  const twoFactorControllerVerify = (verifyTotpDto: VerifyTotpDto) => {
    return customInstance<VerifyTotpResponseDto>({
      url: `/two-factor/verify`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: verifyTotpDto,
    });
  };
  /**
   * @summary 获取 2FA 状态
   */
  const twoFactorControllerGetStatus = () => {
    return customInstance<TwoFactorStatusDto>({
      url: `/two-factor/status`,
      method: "GET",
    });
  };
  /**
   * @summary 重新生成备份码
   */
  const twoFactorControllerRegenerateBackupCodes = (
    verifyTotpDto: VerifyTotpDto,
  ) => {
    return customInstance<BackupCodesDto>({
      url: `/two-factor/regenerate-backup-codes`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: verifyTotpDto,
    });
  };
  /**
   * @summary 验证敏感操作的 TOTP
   */
  const twoFactorControllerVerifyOperation = (verifyTotpDto: VerifyTotpDto) => {
    return customInstance<VerifyTotpResponseDto>({
      url: `/two-factor/verify-operation`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: verifyTotpDto,
    });
  };
  return {
    twoFactorControllerSetup,
    twoFactorControllerEnable,
    twoFactorControllerDisable,
    twoFactorControllerVerify,
    twoFactorControllerGetStatus,
    twoFactorControllerRegenerateBackupCodes,
    twoFactorControllerVerifyOperation,
  };
};
export type TwoFactorControllerSetupResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getTwoFactor>["twoFactorControllerSetup"]>
  >
>;
export type TwoFactorControllerEnableResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getTwoFactor>["twoFactorControllerEnable"]>
  >
>;
export type TwoFactorControllerDisableResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getTwoFactor>["twoFactorControllerDisable"]>
  >
>;
export type TwoFactorControllerVerifyResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getTwoFactor>["twoFactorControllerVerify"]>
  >
>;
export type TwoFactorControllerGetStatusResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getTwoFactor>["twoFactorControllerGetStatus"]>
  >
>;
export type TwoFactorControllerRegenerateBackupCodesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getTwoFactor
      >["twoFactorControllerRegenerateBackupCodes"]
    >
  >
>;
export type TwoFactorControllerVerifyOperationResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getTwoFactor>["twoFactorControllerVerifyOperation"]
    >
  >
>;
