/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateUserDto,
  PaginatedUsersDto,
  ResetPasswordDto,
  UpdatePasswordDto,
  UpdateUserDto,
  UserEntity,
  UsersControllerFindAllParams,
} from "../../models";

import { customInstance } from "../api-client";

export const getUsers = () => {
  /**
   * @summary 创建用户
   */
  const usersControllerCreate = (createUserDto: CreateUserDto) => {
    return customInstance<UserEntity>({
      url: `/users`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createUserDto,
    });
  };
  /**
   * @summary 分页查询用户列表
   */
  const usersControllerFindAll = (params?: UsersControllerFindAllParams) => {
    return customInstance<PaginatedUsersDto>({
      url: `/users`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取用户详情
   */
  const usersControllerFindOne = (id: string) => {
    return customInstance<UserEntity>({ url: `/users/${id}`, method: "GET" });
  };
  /**
   * @summary 更新用户
   */
  const usersControllerUpdate = (id: string, updateUserDto: UpdateUserDto) => {
    return customInstance<UserEntity>({
      url: `/users/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateUserDto,
    });
  };
  /**
   * @summary 删除用户
   */
  const usersControllerRemove = (id: string) => {
    return customInstance<void>({ url: `/users/${id}`, method: "DELETE" });
  };
  /**
   * @summary 重置用户密码
   */
  const usersControllerResetPassword = (
    id: string,
    resetPasswordDto: ResetPasswordDto,
  ) => {
    return customInstance<void>({
      url: `/users/${id}/reset-password`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: resetPasswordDto,
    });
  };
  /**
   * @summary 修改当前用户密码（需要 2FA）
   */
  const usersControllerUpdatePassword = (
    updatePasswordDto: UpdatePasswordDto,
  ) => {
    return customInstance<void>({
      url: `/users/me/password`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: updatePasswordDto,
    });
  };
  return {
    usersControllerCreate,
    usersControllerFindAll,
    usersControllerFindOne,
    usersControllerUpdate,
    usersControllerRemove,
    usersControllerResetPassword,
    usersControllerUpdatePassword,
  };
};
export type UsersControllerCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>["usersControllerCreate"]>>
>;
export type UsersControllerFindAllResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>["usersControllerFindAll"]>>
>;
export type UsersControllerFindOneResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>["usersControllerFindOne"]>>
>;
export type UsersControllerUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>["usersControllerUpdate"]>>
>;
export type UsersControllerRemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>["usersControllerRemove"]>>
>;
export type UsersControllerResetPasswordResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getUsers>["usersControllerResetPassword"]>
  >
>;
export type UsersControllerUpdatePasswordResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getUsers>["usersControllerUpdatePassword"]>
  >
>;
