/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateWebhookConfigDto,
  SendWebhookDto,
  TestWebhookDto,
  UpdateWebhookConfigDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getWebhook = () => {
  /**
   * @summary 发送 Webhook 消息
   */
  const webhooksControllerSendMessage = (sendWebhookDto: SendWebhookDto) => {
    return customInstance<void>({
      url: `/webhook/send`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: sendWebhookDto,
    });
  };
  /**
   * @summary 获取 Webhook 配置列表
   */
  const webhooksControllerFindConfigs = () => {
    return customInstance<void>({ url: `/webhook/configs`, method: "GET" });
  };
  /**
   * @summary 创建 Webhook 配置
   */
  const webhooksControllerCreateConfig = (
    createWebhookConfigDto: CreateWebhookConfigDto,
  ) => {
    return customInstance<void>({
      url: `/webhook/configs`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createWebhookConfigDto,
    });
  };
  /**
   * @summary 更新 Webhook 配置
   */
  const webhooksControllerUpdateConfig = (
    id: string,
    updateWebhookConfigDto: UpdateWebhookConfigDto,
  ) => {
    return customInstance<void>({
      url: `/webhook/configs/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateWebhookConfigDto,
    });
  };
  /**
   * @summary 删除 Webhook 配置
   */
  const webhooksControllerRemoveConfig = (id: string) => {
    return customInstance<void>({
      url: `/webhook/configs/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 测试 Webhook 发送
   */
  const webhooksControllerTestSend = (testWebhookDto: TestWebhookDto) => {
    return customInstance<void>({
      url: `/webhook/test`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: testWebhookDto,
    });
  };
  return {
    webhooksControllerSendMessage,
    webhooksControllerFindConfigs,
    webhooksControllerCreateConfig,
    webhooksControllerUpdateConfig,
    webhooksControllerRemoveConfig,
    webhooksControllerTestSend,
  };
};
export type WebhooksControllerSendMessageResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getWebhook>["webhooksControllerSendMessage"]>
  >
>;
export type WebhooksControllerFindConfigsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getWebhook>["webhooksControllerFindConfigs"]>
  >
>;
export type WebhooksControllerCreateConfigResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getWebhook>["webhooksControllerCreateConfig"]>
  >
>;
export type WebhooksControllerUpdateConfigResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getWebhook>["webhooksControllerUpdateConfig"]>
  >
>;
export type WebhooksControllerRemoveConfigResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getWebhook>["webhooksControllerRemoveConfig"]>
  >
>;
export type WebhooksControllerTestSendResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getWebhook>["webhooksControllerTestSend"]>
  >
>;
