/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface AssignDto {
  /** 客户ID */
  customerId: string;
  /** 新跟进人ID */
  newFollowUserId: string;
  /** 分配原因 */
  reason?: string;
}
