/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface BackupCodesDto {
  /** 备份码列表 */
  backupCodes: string[];
  /** 警告：这些备份码只会显示一次，请妥善保存 */
  warning: string;
}
