/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { BatchUpdateCustomersDtoCustomerLevel } from "./batchUpdateCustomersDtoCustomerLevel";
import type { BatchUpdateCustomersDtoStatus } from "./batchUpdateCustomersDtoStatus";

export interface BatchUpdateCustomersDto {
  /** 客户ID列表 */
  customerIds: string[];
  /** 客户等级 */
  customerLevel?: BatchUpdateCustomersDtoCustomerLevel;
  /** 跟进人ID */
  followUserId?: string;
  /** 来源渠道 */
  sourceChannel?: string;
  /** 行业 */
  industry?: string;
  /** 状态 */
  status?: BatchUpdateCustomersDtoStatus;
}
