/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 操作类型
 */
export type BatchTagsCustomersDtoOperation =
  (typeof BatchTagsCustomersDtoOperation)[keyof typeof BatchTagsCustomersDtoOperation];

export const BatchTagsCustomersDtoOperation = {
  add: "add",
  replace: "replace",
  remove: "remove",
} as const;
