/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { BatchTagsCustomersDtoOperation } from "./batchTagsCustomersDtoOperation";

export interface BatchTagsCustomersDto {
  /** 客户ID列表 */
  customerIds: string[];
  /** 标签（JSON数组字符串） */
  tags: string;
  /** 操作类型 */
  operation: BatchTagsCustomersDtoOperation;
}
