/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export type CmsControllerGetArticlesStatus =
  (typeof CmsControllerGetArticlesStatus)[keyof typeof CmsControllerGetArticlesStatus];

export const CmsControllerGetArticlesStatus = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
} as const;
