/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { CmsControllerGetPageElementsContentType } from "./cmsControllerGetPageElementsContentType";
import type { CmsControllerGetPageElementsStatus } from "./cmsControllerGetPageElementsStatus";

export type CmsControllerGetPageElementsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
  /**
   * 搜索关键词
   */
  keyword?: string;
  /**
   * 内容类型
   */
  contentType?: CmsControllerGetPageElementsContentType;
  /**
   * 状态
   */
  status?: CmsControllerGetPageElementsStatus;
  /**
   * 标签ID筛选
   */
  tagId?: string;
  /**
   * 作者ID筛选
   */
  authorId?: string;
};
