/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { CmsControllerGetArticlesContentType } from "./cmsControllerGetArticlesContentType";
import type { CmsControllerGetArticlesStatus } from "./cmsControllerGetArticlesStatus";

export type CmsControllerGetArticlesParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
  /**
   * 搜索关键词
   */
  keyword?: string;
  /**
   * 内容类型
   */
  contentType?: CmsControllerGetArticlesContentType;
  /**
   * 状态
   */
  status?: CmsControllerGetArticlesStatus;
  /**
   * 标签ID筛选
   */
  tagId?: string;
  /**
   * 作者ID筛选
   */
  authorId?: string;
};
