/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export type CmsPublicControllerGetPublishedProfilesContentType =
  (typeof CmsPublicControllerGetPublishedProfilesContentType)[keyof typeof CmsPublicControllerGetPublishedProfilesContentType];

export const CmsPublicControllerGetPublishedProfilesContentType = {
  ARTICLE: "ARTICLE",
  CASE_STUDY: "CASE_STUDY",
  PRODUCT_SHOWCASE: "PRODUCT_SHOWCASE",
  PROFILE: "PROFILE",
  PAGE_ELEMENT: "PAGE_ELEMENT",
} as const;
