/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface ContractItemDto {
  /** 产品ID */
  productId: string;
  /**
   * 数量
   * @minimum 1
   */
  quantity: number;
  /** 产品原价（划线价格） */
  originalPrice: number;
  /** 实际成交价 */
  actualPrice: number;
}
