/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { ContractControllerFindAllStatus } from "./contractControllerFindAllStatus";

export type ContractControllerFindAllParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
  /**
   * 搜索关键词
   */
  keyword?: string;
  /**
   * 客户ID
   */
  customerId?: string;
  /**
   * 产品ID
   */
  productId?: string;
  /**
   * 合同状态
   */
  status?: ContractControllerFindAllStatus;
};
