/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export type ContactControllerFindAllParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
  /**
   * 搜索关键词
   */
  keyword?: string;
  /**
   * 公司ID筛选
   */
  customerId?: string;
  /**
   * 排序字段
   */
  sortField?: string;
  /**
   * 排序方向
   */
  sortOrder?: string;
};
