/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { CreatePaymentDtoMethod } from "./createPaymentDtoMethod";

export interface CreatePaymentDto {
  /** 合同ID */
  contractId: string;
  /** 收款金额 */
  amount: number;
  /** 收款方式 */
  method: CreatePaymentDtoMethod;
  /** 凭证URL */
  voucherUrl?: string;
  /** 付款时间 */
  payTime?: string;
  /** 备注 */
  remark?: string;
}
