/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 状态
 */
export type CreateUserDtoStatus =
  (typeof CreateUserDtoStatus)[keyof typeof CreateUserDtoStatus];

export const CreateUserDtoStatus = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
} as const;
