/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface CreatePageElementDto {
  /** 区域类型 */
  sectionType: string;
  /** 元素类型 */
  elementType: string;
  /** 排序 */
  sortOrder?: number;
  /** 元素内容（JSON格式） */
  content?: string;
  /** 样式配置（JSON格式） */
  styleConfig?: string;
  /** 是否显示 */
  visible?: boolean;
}
