/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface CreateCmsTagDto {
  /** 标签名称 */
  name: string;
  /** URL别名 */
  slug: string;
  /** 标签颜色 */
  color?: string;
  /** 排序 */
  sortOrder?: number;
}
