/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { CreateServiceTeamDtoRoleCode } from "./createServiceTeamDtoRoleCode";

export interface CreateServiceTeamDto {
  /** 客户ID */
  customerId: string;
  /** 用户ID */
  userId: string;
  /** 角色代码 */
  roleCode: CreateServiceTeamDtoRoleCode;
}
