/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { ContractItemDto } from "./contractItemDto";

export interface CreateContractDto {
  /** 客户ID */
  customerId: string;
  /** 合同产品列表 */
  items: ContractItemDto[];
  /** 合同模板ID */
  templateId?: string;
  /** 服务开始日期 */
  serviceStart: string;
  /** 服务结束日期 */
  serviceEnd: string;
  /** 备注 */
  remark?: string;
}
