/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 定价类型
 */
export type CreateProductDtoPricingType =
  (typeof CreateProductDtoPricingType)[keyof typeof CreateProductDtoPricingType];

export const CreateProductDtoPricingType = {
  FIXED: "FIXED",
  TIER_AMOUNT: "TIER_AMOUNT",
  TIER_COUNT: "TIER_COUNT",
  ZERO_DECLARATION: "ZERO_DECLARATION",
} as const;
