/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface CreateCustomerRuleDto {
  /** 规则唯一标识 */
  code: string;
  /** 规则标题 */
  title: string;
  /** 规则描述 */
  description?: string;
  /** 天数数值 */
  daysValue: number;
  /** 是否启用 */
  enabled: boolean;
}
