/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface CreatePaymentOrderDto {
  /** 关联合同ID */
  contractId?: string;
  /** 支付金额 */
  amount: number;
  /** 支付方式: wechat, alipay, bank */
  paymentMethod: string;
  /** 支付渠道 */
  paymentChannel?: string;
  /** 客户端IP */
  clientIp?: string;
  /** 支付完成跳转URL */
  returnUrl?: string;
  /** 异步通知URL */
  notifyUrl?: string;
  /** 订单描述 */
  body?: string;
  /** 附加数据 */
  attach?: string;
}
