/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface CreateContractTemplateDto {
  /** 模板名称 */
  name: string;
  /** 模板编码 */
  code: string;
  /** 合同内容 */
  content: string;
  /** 变量定义(JSON) */
  variables?: string;
  /** 模板描述 */
  description?: string;
}
