/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface CreateSocialMediaAccountDto {
  /** 平台: douyin, xiaohongshu, wechat */
  platform: string;
  /** 账号名称 */
  accountName: string;
  /** 应用ID */
  appId?: string;
  /** 应用密钥 */
  appSecret?: string;
  /** 访问令牌 */
  accessToken?: string;
  /** 刷新令牌 */
  refreshToken?: string;
  /** 平台账号ID */
  accountId?: string;
  /** 开放ID */
  openId?: string;
  /** 联合ID */
  unionId?: string;
  /** 令牌过期时间（ISO 8601格式） */
  expiresAt?: string;
}
