/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 可见性
 */
export type CreateSocialMediaPostDtoVisibility =
  (typeof CreateSocialMediaPostDtoVisibility)[keyof typeof CreateSocialMediaPostDtoVisibility];

export const CreateSocialMediaPostDtoVisibility = {
  public: "public",
  friends: "friends",
  private: "private",
} as const;
