/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { CreateCmsContentDtoContentType } from "./createCmsContentDtoContentType";
import type { CreateCmsContentDtoStatus } from "./createCmsContentDtoStatus";

export interface CreateCmsContentDto {
  /** 标题 */
  title: string;
  /** URL别名 */
  slug: string;
  /** 内容 */
  content: string;
  /** 摘要 */
  excerpt?: string;
  /** 封面图URL */
  coverImage?: string;
  /** 状态 */
  status?: CreateCmsContentDtoStatus;
  /** 内容类型 */
  contentType: CreateCmsContentDtoContentType;
  /** 关联产品ID（仅PRODUCT_SHOWCASE类型使用） */
  productId?: string;
  /** 关联用户ID（仅PROFILE类型使用） */
  userId?: string;
  /** 关联合同ID（仅CASE_STUDY类型使用，展示客户案例） */
  contractId?: string;
  /** SEO标题 */
  metaTitle?: string;
  /** SEO描述 */
  metaDesc?: string;
  /** 关键词 */
  keywords?: string;
  /** 标签ID数组 */
  tagIds?: string[];
}
