/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { CreateCustomerDtoCustomerLevel } from "./createCustomerDtoCustomerLevel";

export interface CreateCustomerDto {
  /** 公司名称 */
  name: string;
  /** 公司简称 */
  shortName?: string;
  /** 公司编码 */
  code?: string;
  /** 所属行业 */
  industry?: string;
  /** 公司规模 */
  scale?: string;
  /** 公司地址 */
  address?: string;
  /** 公司网站 */
  website?: string;
  /** 客户等级 */
  customerLevel?: CreateCustomerDtoCustomerLevel;
  /** 来源渠道 */
  sourceChannel?: string;
  /** 跟进人ID */
  followUserId?: string;
  /** 标签（JSON数组） */
  tags?: string;
  /** 备注 */
  remark?: string;
}
