/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { CreateCmsPageDtoStatus } from "./createCmsPageDtoStatus";
import type { CreateCmsPageDtoTemplate } from "./createCmsPageDtoTemplate";
import type { CreatePageElementDto } from "./createPageElementDto";

export interface CreateCmsPageDto {
  /** 页面名称（内部标识） */
  name: string;
  /** 页面标题 */
  title: string;
  /** URL路径 */
  slug: string;
  /** 页面描述 */
  description?: string;
  /** 状态 */
  status?: CreateCmsPageDtoStatus;
  /**
   * SEO 标题
   * @maxLength 60
   */
  metaTitle?: string;
  /**
   * SEO 描述
   * @maxLength 160
   */
  metaDesc?: string;
  /** 关键词 */
  keywords?: string;
  /** OG 图片 URL */
  ogImage?: string;
  /** 页面模板 */
  template?: CreateCmsPageDtoTemplate;
  /** 页面元素 */
  elements?: CreatePageElementDto[];
}
