/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface CreateMenuDto {
  /** 路由路径 */
  path: string;
  /** 菜单名称 */
  name: string;
  /** 分组标题 */
  groupTitle: string;
  /** 国际化key */
  i18nKey?: string;
  /** 图标名称 */
  icon?: string;
  /** 父级菜单ID */
  parentId?: string;
  /** 排序 */
  sort?: number;
  /** 是否启用 */
  enabled?: boolean;
  /** 是否有子菜单 */
  hasChildren?: boolean;
  /** 关联权限ID列表 */
  permissionIds?: string[];
  /** 菜单类型（menu: 菜单, button: 按钮, group: 分组） */
  type?: string;
  /** 权限代码 */
  permissionCode?: string;
}
