/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { CustomerControllerExportCustomersCustomerLevel } from "./customerControllerExportCustomersCustomerLevel";
import type { CustomerControllerExportCustomersStatus } from "./customerControllerExportCustomersStatus";

export type CustomerControllerExportCustomersParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
  /**
   * 搜索关键词
   */
  keyword?: string;
  /**
   * 客户等级
   */
  customerLevel?: CustomerControllerExportCustomersCustomerLevel;
  /**
   * 客户状态
   */
  status?: CustomerControllerExportCustomersStatus;
  /**
   * 跟进人ID
   */
  followUserId?: string;
  /**
   * 排序字段
   */
  sortField?: string;
  /**
   * 排序方向
   */
  sortOrder?: string;
};
