/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export type CustomerControllerFindAllCustomerLevel =
  (typeof CustomerControllerFindAllCustomerLevel)[keyof typeof CustomerControllerFindAllCustomerLevel];

export const CustomerControllerFindAllCustomerLevel = {
  LEAD: "LEAD",
  PROSPECT: "PROSPECT",
  CUSTOMER: "CUSTOMER",
  VIP: "VIP",
} as const;
