/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface DashboardMonthlyDto {
  /** 本月新增客户 */
  newCustomers: number;
  /** 本月新增合同 */
  newContracts: number;
  /** 本月合同金额 */
  contractAmount: number;
  /** 本月开票金额 */
  invoiceAmount: number;
}
