/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface DashboardOverviewDto {
  /** 总客户数 */
  totalCustomers: number;
  /** 合同总数 */
  totalContracts: number;
  /** 产品总数 */
  totalProducts: number;
  /** 开票记录总数 */
  totalInvoices: number;
}
