/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { DashboardMonthlyDto } from "./dashboardMonthlyDto";
import type { DashboardOverviewDto } from "./dashboardOverviewDto";

export interface DashboardStatsDto {
  /** 总览数据 */
  overview: DashboardOverviewDto;
  /** 本月数据 */
  monthly: DashboardMonthlyDto;
  /** 最近活动 */
  recentActivities: unknown[][];
  /** 未读通知数 */
  unreadNotifications: number;
}
