/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface Enable2faDto {
  /** TOTP 密钥 */
  secret: string;
  /**
   * 6位验证码
   * @minLength 6
   * @maxLength 6
   */
  token: string;
}
