/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { EsignControllerInitiateSigningBodySignersItem } from "./esignControllerInitiateSigningBodySignersItem";

export type EsignControllerInitiateSigningBody = {
  file?: Blob;
  /** 合同ID */
  contractId?: string;
  /** 签署人列表 */
  signers?: EsignControllerInitiateSigningBodySignersItem[];
  /** 合同标题 */
  subject?: string;
  /** 合同描述 */
  description?: string;
  /** 备注 */
  remark?: string;
};
