/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { EsignControllerInitiateSigningBodySignersItemSignerType } from "./esignControllerInitiateSigningBodySignersItemSignerType";

export type EsignControllerInitiateSigningBodySignersItem = {
  name?: string;
  mobile?: string;
  signerType?: EsignControllerInitiateSigningBodySignersItemSignerType;
  organization?: string;
  idCard?: string;
};
