/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { ExportLogDtoType } from "./exportLogDtoType";

export interface ExportLogDto {
  /** 日志类型 */
  type: ExportLogDtoType;
  /** 开始时间 (YYYY-MM-DD) */
  startDate?: string;
  /** 结束时间 (YYYY-MM-DD) */
  endDate?: string;
}
