/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 日志类型
 */
export type ExportLogDtoType =
  (typeof ExportLogDtoType)[keyof typeof ExportLogDtoType];

export const ExportLogDtoType = {
  operation: "operation",
  system: "system",
} as const;
