/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface InitializeResultResponse {
  /** 菜单创建数量 */
  menusCreated: number;
  /** 菜单更新数量 */
  menusUpdated: number;
  /** 权限创建数量 */
  permissionsCreated: number;
  /** 权限跳过数量 */
  permissionsSkipped: number;
}
