/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { InvoiceControllerFindAllStatus } from "./invoiceControllerFindAllStatus";

export type InvoiceControllerFindAllParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
  /**
   * 客户ID
   */
  customerId?: string;
  /**
   * 合同ID
   */
  contractId?: string;
  /**
   * 发票状态
   */
  status?: InvoiceControllerFindAllStatus;
  /**
   * 开票月份(YYYY-MM)
   */
  month?: string;
};
