/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface LinkCompanyDto {
  /** 公司ID */
  customerId: string;
  /** 是否主要联系人 */
  isPrimary?: boolean;
  /** 是否决策人 */
  isDecision?: boolean;
  /** 在该公司的部门 */
  department?: string;
  /** 在该公司的职位 */
  position?: string;
  /** 与公司关系（法人/股东/采购负责人/财务等） */
  relation?: string;
  /** 标签 */
  tags?: string;
  /** 备注 */
  remark?: string;
}
