/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface LinkContactDto {
  /** 联系人ID */
  contactId: string;
  /** 是否主要联系人 */
  isPrimary?: boolean;
  /** 是否决策人 */
  isDecision?: boolean;
  /** 在该公司的部门 */
  department?: string;
  /** 在该公司的职位 */
  position?: string;
  /** 与公司关系 */
  relation?: string;
  /** 备注 */
  remark?: string;
}
