/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { LoginUserDto } from "./loginUserDto";

export interface LoginResponseDto {
  /** 访问令牌 */
  access_token: string;
  /** 用户信息 */
  user: LoginUserDto;
  /** 是否需要强制修改密码（仅系统用户首次登录） */
  requiresPasswordChange?: boolean;
  /** 是否需要强制设置 2FA（仅系统用户首次登录，改密码后） */
  requiresTwoFactorSetup?: boolean;
}
