/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
}
