/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export type LogsControllerFindSystemLogsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
  /**
   * 日志级别: INFO, WARN, ERROR, DEBUG
   */
  level?: string;
  /**
   * 模块名
   */
  module?: string;
  /**
   * 开始时间 (YYYY-MM-DD)
   */
  startDate?: string;
  /**
   * 结束时间 (YYYY-MM-DD)
   */
  endDate?: string;
};
