/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export type LogsControllerFindOperationLogsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
  /**
   * 用户ID
   */
  userId?: string;
  /**
   * 操作类型
   */
  action?: string;
  /**
   * 资源类型
   */
  resource?: string;
  /**
   * 开始时间 (YYYY-MM-DD)
   */
  startDate?: string;
  /**
   * 结束时间 (YYYY-MM-DD)
   */
  endDate?: string;
};
