/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { MenuDetailDtoPermissionsItem } from "./menuDetailDtoPermissionsItem";
import type { MenuItemDto } from "./menuItemDto";

export interface MenuDetailDto {
  /** 菜单ID */
  id: string;
  /** 路由路径 */
  path: string;
  /** 菜单名称 */
  name: string;
  /** 菜单标题 */
  title: string;
  /** 国际化key */
  i18nKey?: string;
  /** 图标名称 */
  icon?: string;
  /** 徽章文本 */
  badge?: string;
  /** 排序 */
  sort: number;
  /** 是否启用 */
  enabled: boolean;
  /** 父级菜单ID */
  parentId?: string;
  /** 分组标题 */
  groupTitle?: string;
  /** 是否隐藏 */
  isHidden: boolean;
  /** 是否系统菜单 */
  isSystem: boolean;
  /** 状态(0:禁用 1:启用) */
  status: number;
  /** 创建时间 */
  createdAt: Date;
  /** 更新时间 */
  updatedAt: Date;
  /** 关联的权限列表 */
  permissions?: MenuDetailDtoPermissionsItem[];
  /** 子菜单列表 */
  children?: MenuItemDto[];
}
