/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface MenuItemDto {
  /** 菜单ID */
  id: string;
  /** 路由路径 */
  path: string;
  /** 菜单名称 */
  name: string;
  /** 菜单标题 */
  title: string;
  /** 国际化key */
  i18nKey?: string;
  /** 图标名称 */
  icon?: string;
  /** 徽章文本 */
  badge?: string;
  /** 排序 */
  sort: number;
  /** 是否启用 */
  enabled: boolean;
}
