/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { MenuItemDto } from "./menuItemDto";

export interface MenuGroupDto {
  /** 分组标题 */
  title: string;
  /** 国际化key */
  i18nKey?: string;
  /** 菜单项列表 */
  items: MenuItemDto[];
}
