/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { PaymentControllerFindAllMethod } from "./paymentControllerFindAllMethod";
import type { PaymentControllerFindAllStatus } from "./paymentControllerFindAllStatus";

export type PaymentControllerFindAllParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
  /**
   * 合同ID
   */
  contractId?: string;
  /**
   * 收款方式
   */
  method?: PaymentControllerFindAllMethod;
  /**
   * 收款状态
   */
  status?: PaymentControllerFindAllStatus;
};
