/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export type PaymentOrderControllerFindAllParams = {
  /**
   * 关联合同ID
   */
  contractId?: string;
  /**
   * 订单号
   */
  orderNo?: string;
  /**
   * 支付方式
   */
  paymentMethod?: string;
  /**
   * 支付状态
   */
  status?: string;
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
};
