/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface RefundDto {
  /** 订单ID */
  orderId: string;
  /** 退款金额 */
  amount: number;
  /** 退款原因 */
  reason?: string;
}
