/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { MenuOrderItemDto } from "./menuOrderItemDto";

export interface ReorderMenuDto {
  /** 菜单排序项列表 */
  items: MenuOrderItemDto[];
}
