/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface SchedulePublishDto {
  /** 内容ID */
  id: string;
  /** 定时发布时间（ISO 8601格式） */
  scheduledAt: string;
}
