/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { SendWebhookDtoContent } from "./sendWebhookDtoContent";
import type { SendWebhookDtoMessageType } from "./sendWebhookDtoMessageType";

export interface SendWebhookDto {
  /** Webhook 配置 ID */
  configId: string;
  /** 消息类型 */
  messageType: SendWebhookDtoMessageType;
  /** 消息内容 */
  content: SendWebhookDtoContent;
}
