/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 消息类型
 */
export type SendWebhookDtoMessageType =
  (typeof SendWebhookDtoMessageType)[keyof typeof SendWebhookDtoMessageType];

export const SendWebhookDtoMessageType = {
  text: "text",
  markdown: "markdown",
  card: "card",
} as const;
