/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface Setup2faResponseDto {
  /** TOTP 密钥（用于手动输入） */
  secret: string;
  /** 二维码 URL（用于扫描） */
  qrCodeUrl: string;
  /** 应用名称 */
  appName: string;
  /** 用户账户名 */
  accountName: string;
}
