/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export type StatisticsControllerExportDataType =
  (typeof StatisticsControllerExportDataType)[keyof typeof StatisticsControllerExportDataType];

export const StatisticsControllerExportDataType = {
  customers: "customers",
  contracts: "contracts",
  invoices: "invoices",
} as const;
