/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface SubmitContactDto {
  /** 联系人姓名 */
  name: string;
  /** 联系电话 */
  phone: string;
  /** 联系邮箱 */
  email?: string;
  /** 公司名称 */
  company?: string;
  /** 留言内容 */
  message: string;
}
