/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export type SystemLogsControllerGetLogsParams = {
  /**
   * 搜索关键词
   */
  search?: string;
  /**
   * 日志级别过滤 (error/warn/info/all)
   */
  level?: string;
  /**
   * 返回的日志行数 (1-1000, 默认100)
   */
  lines?: number;
};
