/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface TwoFactorStatusDto {
  /** 是否启用 2FA */
  enabled: boolean;
  /** 是否已完成首次登录设置 */
  hasCompletedFirstLogin?: boolean;
  /** 2FA 设置完成时间 */
  setupCompletedAt?: Date;
}
