/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface UpdatePaymentConfigDto {
  /** 应用密钥 */
  appSecret?: string;
  /** API密钥 */
  apiKey?: string;
  /** 证书路径 */
  certPath?: string;
  /** 默认回调地址 */
  notifyUrl?: string;
  /** 默认返回地址 */
  returnUrl?: string;
  /** 是否沙箱环境 */
  sandbox?: boolean;
  /** 状态 0:禁用 1:启用 */
  status?: number;
}
