/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface UpdateInvoiceDto {
  /** 客户ID */
  customerId?: string;
  /** 合同ID(可选) */
  contractId?: string;
  /** 开票金额 */
  amount?: number;
  /** 开票张数 */
  count?: number;
  /** 开票月份(YYYY-MM) */
  month?: string;
  /** 备注 */
  remark?: string;
}
