/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { UpdateSocialMediaPostDtoStatus } from "./updateSocialMediaPostDtoStatus";

export interface UpdateSocialMediaPostDto {
  /** 标题 */
  title?: string;
  /** 文案内容 */
  content?: string;
  /** 视频文件ID */
  videoFileId?: string;
  /** 封面图文件ID */
  coverFileId?: string;
  /** 视频URL */
  videoUrl?: string;
  /** 封面图URL */
  coverUrl?: string;
  /** 话题标签 */
  topics?: string[];
  /** 位置信息 */
  location?: string;
  /** 可见性 */
  visibility?: string;
  /** 定时发布时间 */
  scheduledAt?: string;
  /** 状态 */
  status?: UpdateSocialMediaPostDtoStatus;
}
