/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 状态
 */
export type UpdateSocialMediaPostDtoStatus =
  (typeof UpdateSocialMediaPostDtoStatus)[keyof typeof UpdateSocialMediaPostDtoStatus];

export const UpdateSocialMediaPostDtoStatus = {
  draft: "draft",
  scheduled: "scheduled",
  publishing: "publishing",
  published: "published",
  failed: "failed",
} as const;
