/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 状态
 */
export type UpdateCmsContentDtoStatus =
  (typeof UpdateCmsContentDtoStatus)[keyof typeof UpdateCmsContentDtoStatus];

export const UpdateCmsContentDtoStatus = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
} as const;
