/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 角色代码
 */
export type UpdateServiceTeamDtoRoleCode =
  (typeof UpdateServiceTeamDtoRoleCode)[keyof typeof UpdateServiceTeamDtoRoleCode];

export const UpdateServiceTeamDtoRoleCode = {
  SALE: "SALE",
  FINANCE: "FINANCE",
  OUTWORK: "OUTWORK",
} as const;
