/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { UpdateWebhookConfigDtoPlatform } from "./updateWebhookConfigDtoPlatform";

export interface UpdateWebhookConfigDto {
  /** 配置名称 */
  name?: string;
  /** 平台 */
  platform?: UpdateWebhookConfigDtoPlatform;
  /** Webhook URL */
  webhookUrl?: string;
  /** 是否启用 */
  enabled?: boolean;
}
