/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 页面模板
 */
export type UpdateCmsPageDtoTemplate =
  (typeof UpdateCmsPageDtoTemplate)[keyof typeof UpdateCmsPageDtoTemplate];

export const UpdateCmsPageDtoTemplate = {
  homepage: "homepage",
  about: "about",
  contact: "contact",
  custom: "custom",
} as const;
