/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { UpdateProductDtoPricingType } from "./updateProductDtoPricingType";

export interface UpdateProductDto {
  /** 产品名称 */
  name?: string;
  /** 产品代码 */
  code?: string;
  /** 产品描述 */
  description?: string;
  /** 基础价格 */
  price?: number;
  /** 产品时间轴(JSON数组) */
  timeline?: string;
  /** 定价类型 */
  pricingType?: UpdateProductDtoPricingType;
  /** 服务负责人角色ID */
  serviceRoleId?: string;
  /** 产品图片ID */
  imageId?: string;
}
