/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 流程类型
 */
export type UpdateProductFlowDtoType =
  (typeof UpdateProductFlowDtoType)[keyof typeof UpdateProductFlowDtoType];

export const UpdateProductFlowDtoType = {
  NODE: "NODE",
  CYCLE: "CYCLE",
} as const;
