/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface UpdateContactRoleDto {
  /** 是否主要联系人 */
  isPrimary?: boolean;
  /** 是否决策人 */
  isDecision?: boolean;
  /** 部门 */
  department?: string;
  /** 职位 */
  position?: string;
  /** 与公司关系 */
  relation?: string;
  /** 状态: 1在职 0离职 */
  status?: number;
  /** 备注 */
  remark?: string;
}
