/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 平台
 */
export type UpdateWebhookConfigDtoPlatform =
  (typeof UpdateWebhookConfigDtoPlatform)[keyof typeof UpdateWebhookConfigDtoPlatform];

export const UpdateWebhookConfigDtoPlatform = {
  wecom: "wecom",
  feishu: "feishu",
  dingtalk: "dingtalk",
} as const;
