/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface UpdateFollowRecordDto {
  /** 跟进类型: 1:电话 2:微信 3:上门 4:邮件 5:其他 */
  type?: number;
  /** 跟进内容 */
  content?: string;
  /** 下次跟进时间 */
  nextTime?: string;
  /** 图片(JSON数组) */
  images?: string;
}
