/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 支付状态
 */
export type UpdatePaymentOrderDtoStatus =
  (typeof UpdatePaymentOrderDtoStatus)[keyof typeof UpdatePaymentOrderDtoStatus];

export const UpdatePaymentOrderDtoStatus = {
  pending: "pending",
  paid: "paid",
  cancelled: "cancelled",
  refunded: "refunded",
  expired: "expired",
} as const;
