/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 收款方式
 */
export type UpdatePaymentDtoMethod =
  (typeof UpdatePaymentDtoMethod)[keyof typeof UpdatePaymentDtoMethod];

export const UpdatePaymentDtoMethod = {
  BANK_TRANSFER: "BANK_TRANSFER",
  WECHAT: "WECHAT",
  ALIPAY: "ALIPAY",
  CASH: "CASH",
} as const;
