/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 客户等级
 */
export type UpdateCustomerDtoCustomerLevel =
  (typeof UpdateCustomerDtoCustomerLevel)[keyof typeof UpdateCustomerDtoCustomerLevel];

export const UpdateCustomerDtoCustomerLevel = {
  LEAD: "LEAD",
  PROSPECT: "PROSPECT",
  CUSTOMER: "CUSTOMER",
  VIP: "VIP",
} as const;
