/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserDtoStatus } from "./updateUserDtoStatus";

export interface UpdateUserDto {
  /** 用户名 */
  username?: string;
  /** 密码 */
  password?: string;
  /** 姓名 */
  name?: string;
  /**
   * 邮箱
   * @nullable
   */
  email?: string | null;
  /**
   * 手机号
   * @nullable
   */
  phone?: string | null;
  /** 部门ID */
  departmentId?: string;
  /** 角色ID列表 */
  roleIds?: string[];
  /** 状态 */
  status?: UpdateUserDtoStatus;
}
