/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface UpdateDepartmentDto {
  /** 部门名称 */
  name?: string;
  /** 父部门ID */
  parentId?: string;
  /** 排序 */
  sort?: number;
  /** 状态: ACTIVE启用 INACTIVE禁用 */
  status?: string;
}
