/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { UpdateProductFlowDtoType } from "./updateProductFlowDtoType";

export interface UpdateProductFlowDto {
  /** 产品ID */
  productId?: string;
  /** 流程名称 */
  name?: string;
  /** 流程类型 */
  type?: UpdateProductFlowDtoType;
  /** 流程配置(JSON) */
  config?: string;
  /** 是否启用 */
  enabled?: boolean;
}
