/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { UploadFileDtoFileType } from "./uploadFileDtoFileType";

export interface UploadFileDto {
  /** 文件名 */
  fileName: string;
  /** 文件内容 (Base64) */
  fileContent: string;
  /** 文件类型 */
  fileType?: UploadFileDtoFileType;
  /** MIME 类型 */
  mimeType?: string;
}
