/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 文件类型
 */
export type UploadFileDtoFileType =
  (typeof UploadFileDtoFileType)[keyof typeof UploadFileDtoFileType];

export const UploadFileDtoFileType = {
  image: "image",
  document: "document",
  video: "video",
  other: "other",
} as const;
