/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { UserRoleDto } from "./userRoleDto";

export interface UserRoleWithRelation {
  /** 角色信息 */
  role: UserRoleDto;
}
