/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { DepartmentDto } from "./departmentDto";
import type { UserEntityStatus } from "./userEntityStatus";
import type { UserRoleWithRelation } from "./userRoleWithRelation";

export interface UserEntity {
  /** 用户ID */
  id: string;
  /** 用户名 */
  username: string;
  /** 姓名 */
  name: string;
  /** 邮箱 */
  email?: string;
  /** 手机号 */
  phone?: string;
  /** 头像 */
  avatar?: string;
  /** 部门ID */
  departmentId?: string;
  /** 部门信息 */
  department?: DepartmentDto;
  /** 状态 */
  status: UserEntityStatus;
  /** 是否为系统用户 */
  isSystem?: boolean;
  /** 角色列表 */
  roles?: UserRoleWithRelation[];
  /** 创建时间 */
  createdAt: Date;
  /** 更新时间 */
  updatedAt: Date;
}
