/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface UserRoleDto {
  /** 角色ID */
  id: string;
  /** 角色名称 */
  name: string;
  /** 角色代码 */
  code: string;
}
