/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { UsersControllerFindAllStatus } from "./usersControllerFindAllStatus";

export type UsersControllerFindAllParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
  /**
   * 搜索关键词
   */
  search?: string;
  /**
   * 部门ID
   */
  departmentId?: string;
  /**
   * 状态
   */
  status?: UsersControllerFindAllStatus;
  /**
   * 角色ID
   */
  roleId?: string;
};
