/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface VerifyTotpResponseDto {
  /** 验证是否成功 */
  valid: boolean;
  /** 是否为备份码 */
  isBackupCode?: boolean;
}
