/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Setup2faRouteImport } from './routes/setup-2fa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWebhooksRouteImport } from './routes/_authenticated/webhooks'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AuthenticatedSystemLogsRouteRouteImport } from './routes/_authenticated/system-logs/route'
import { Route as AuthenticatedSocialMediaRouteRouteImport } from './routes/_authenticated/social-media/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedServiceTeamsRouteRouteImport } from './routes/_authenticated/service-teams/route'
import { Route as AuthenticatedRolesRouteRouteImport } from './routes/_authenticated/roles/route'
import { Route as AuthenticatedProductsRouteRouteImport } from './routes/_authenticated/products/route'
import { Route as AuthenticatedPaymentsRouteRouteImport } from './routes/_authenticated/payments/route'
import { Route as AuthenticatedOperationLogsRouteRouteImport } from './routes/_authenticated/operation-logs/route'
import { Route as AuthenticatedMenusRouteRouteImport } from './routes/_authenticated/menus/route'
import { Route as AuthenticatedLoginLogsRouteRouteImport } from './routes/_authenticated/login-logs/route'
import { Route as AuthenticatedInvoicesRouteRouteImport } from './routes/_authenticated/invoices/route'
import { Route as AuthenticatedDepartmentsRouteRouteImport } from './routes/_authenticated/departments/route'
import { Route as AuthenticatedCustomersRouteRouteImport } from './routes/_authenticated/customers/route'
import { Route as AuthenticatedCustomerRulesRouteRouteImport } from './routes/_authenticated/customer-rules/route'
import { Route as AuthenticatedContractsRouteRouteImport } from './routes/_authenticated/contracts/route'
import { Route as AuthenticatedContractTemplatesRouteRouteImport } from './routes/_authenticated/contract-templates/route'
import { Route as AuthenticatedContactsRouteRouteImport } from './routes/_authenticated/contacts/route'
import { Route as AuthenticatedCmsRouteRouteImport } from './routes/_authenticated/cms/route'
import { Route as AuthenticatedAiAgentRouteRouteImport } from './routes/_authenticated/ai-agent/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedCmsIndexRouteImport } from './routes/_authenticated/cms/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedWebhooksTemplatesRouteImport } from './routes/_authenticated/webhooks/templates'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedPaymentsConfigRouteImport } from './routes/_authenticated/payments/config'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCmsTagsRouteRouteImport } from './routes/_authenticated/cms/tags/route'
import { Route as AuthenticatedCmsPagesRouteRouteImport } from './routes/_authenticated/cms/pages/route'
import { Route as AuthenticatedCmsNewRouteRouteImport } from './routes/_authenticated/cms/new/route'
import { Route as AuthenticatedCmsElementsRouteRouteImport } from './routes/_authenticated/cms/elements/route'
import { Route as AuthenticatedRolesRoleIdPermissionsRouteImport } from './routes/_authenticated/roles/$roleId/permissions'
import { Route as AuthenticatedCmsPagesNewRouteRouteImport } from './routes/_authenticated/cms/pages/new/route'
import { Route as AuthenticatedCmsEditIdRouteRouteImport } from './routes/_authenticated/cms/edit/$id/route'
import { Route as AuthenticatedCmsPagesEditPageIdRouteRouteImport } from './routes/_authenticated/cms/pages/edit/$pageId/route'

const Setup2faRoute = Setup2faRouteImport.update({
  id: '/setup-2fa',
  path: '/setup-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebhooksRoute = AuthenticatedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSystemLogsRouteRoute =
  AuthenticatedSystemLogsRouteRouteImport.update({
    id: '/system-logs',
    path: '/system-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSocialMediaRouteRoute =
  AuthenticatedSocialMediaRouteRouteImport.update({
    id: '/social-media',
    path: '/social-media',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServiceTeamsRouteRoute =
  AuthenticatedServiceTeamsRouteRouteImport.update({
    id: '/service-teams',
    path: '/service-teams',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesRouteRoute = AuthenticatedRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRouteRoute =
  AuthenticatedProductsRouteRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRouteRoute =
  AuthenticatedPaymentsRouteRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationLogsRouteRoute =
  AuthenticatedOperationLogsRouteRouteImport.update({
    id: '/operation-logs',
    path: '/operation-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenusRouteRoute = AuthenticatedMenusRouteRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoginLogsRouteRoute =
  AuthenticatedLoginLogsRouteRouteImport.update({
    id: '/login-logs',
    path: '/login-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesRouteRoute =
  AuthenticatedInvoicesRouteRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsRouteRoute =
  AuthenticatedDepartmentsRouteRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRouteRoute =
  AuthenticatedCustomersRouteRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomerRulesRouteRoute =
  AuthenticatedCustomerRulesRouteRouteImport.update({
    id: '/customer-rules',
    path: '/customer-rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsRouteRoute =
  AuthenticatedContractsRouteRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractTemplatesRouteRoute =
  AuthenticatedContractTemplatesRouteRouteImport.update({
    id: '/contract-templates',
    path: '/contract-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsRouteRoute =
  AuthenticatedContactsRouteRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsRouteRoute = AuthenticatedCmsRouteRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiAgentRouteRoute =
  AuthenticatedAiAgentRouteRouteImport.update({
    id: '/ai-agent',
    path: '/ai-agent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsIndexRoute = AuthenticatedCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCmsRouteRoute,
} as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebhooksTemplatesRoute =
  AuthenticatedWebhooksTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedWebhooksRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPaymentsConfigRoute =
  AuthenticatedPaymentsConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedPaymentsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmsTagsRouteRoute =
  AuthenticatedCmsTagsRouteRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => AuthenticatedCmsRouteRoute,
  } as any)
const AuthenticatedCmsPagesRouteRoute =
  AuthenticatedCmsPagesRouteRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => AuthenticatedCmsRouteRoute,
  } as any)
const AuthenticatedCmsNewRouteRoute =
  AuthenticatedCmsNewRouteRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCmsRouteRoute,
  } as any)
const AuthenticatedCmsElementsRouteRoute =
  AuthenticatedCmsElementsRouteRouteImport.update({
    id: '/elements',
    path: '/elements',
    getParentRoute: () => AuthenticatedCmsRouteRoute,
  } as any)
const AuthenticatedRolesRoleIdPermissionsRoute =
  AuthenticatedRolesRoleIdPermissionsRouteImport.update({
    id: '/$roleId/permissions',
    path: '/$roleId/permissions',
    getParentRoute: () => AuthenticatedRolesRouteRoute,
  } as any)
const AuthenticatedCmsPagesNewRouteRoute =
  AuthenticatedCmsPagesNewRouteRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCmsPagesRouteRoute,
  } as any)
const AuthenticatedCmsEditIdRouteRoute =
  AuthenticatedCmsEditIdRouteRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedCmsRouteRoute,
  } as any)
const AuthenticatedCmsPagesEditPageIdRouteRoute =
  AuthenticatedCmsPagesEditPageIdRouteRouteImport.update({
    id: '/edit/$pageId',
    path: '/edit/$pageId',
    getParentRoute: () => AuthenticatedCmsPagesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/setup-2fa': typeof Setup2faRoute
  '/ai-agent': typeof AuthenticatedAiAgentRouteRoute
  '/cms': typeof AuthenticatedCmsRouteRouteWithChildren
  '/contacts': typeof AuthenticatedContactsRouteRoute
  '/contract-templates': typeof AuthenticatedContractTemplatesRouteRoute
  '/contracts': typeof AuthenticatedContractsRouteRoute
  '/customer-rules': typeof AuthenticatedCustomerRulesRouteRoute
  '/customers': typeof AuthenticatedCustomersRouteRoute
  '/departments': typeof AuthenticatedDepartmentsRouteRoute
  '/invoices': typeof AuthenticatedInvoicesRouteRoute
  '/login-logs': typeof AuthenticatedLoginLogsRouteRoute
  '/menus': typeof AuthenticatedMenusRouteRoute
  '/operation-logs': typeof AuthenticatedOperationLogsRouteRoute
  '/payments': typeof AuthenticatedPaymentsRouteRouteWithChildren
  '/products': typeof AuthenticatedProductsRouteRoute
  '/roles': typeof AuthenticatedRolesRouteRouteWithChildren
  '/service-teams': typeof AuthenticatedServiceTeamsRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/social-media': typeof AuthenticatedSocialMediaRouteRoute
  '/system-logs': typeof AuthenticatedSystemLogsRouteRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/webhooks': typeof AuthenticatedWebhooksRouteWithChildren
  '/cms/elements': typeof AuthenticatedCmsElementsRouteRoute
  '/cms/new': typeof AuthenticatedCmsNewRouteRoute
  '/cms/pages': typeof AuthenticatedCmsPagesRouteRouteWithChildren
  '/cms/tags': typeof AuthenticatedCmsTagsRouteRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/payments/config': typeof AuthenticatedPaymentsConfigRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/webhooks/templates': typeof AuthenticatedWebhooksTemplatesRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/cms/': typeof AuthenticatedCmsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/cms/edit/$id': typeof AuthenticatedCmsEditIdRouteRoute
  '/cms/pages/new': typeof AuthenticatedCmsPagesNewRouteRoute
  '/roles/$roleId/permissions': typeof AuthenticatedRolesRoleIdPermissionsRoute
  '/cms/pages/edit/$pageId': typeof AuthenticatedCmsPagesEditPageIdRouteRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/setup-2fa': typeof Setup2faRoute
  '/ai-agent': typeof AuthenticatedAiAgentRouteRoute
  '/contacts': typeof AuthenticatedContactsRouteRoute
  '/contract-templates': typeof AuthenticatedContractTemplatesRouteRoute
  '/contracts': typeof AuthenticatedContractsRouteRoute
  '/customer-rules': typeof AuthenticatedCustomerRulesRouteRoute
  '/customers': typeof AuthenticatedCustomersRouteRoute
  '/departments': typeof AuthenticatedDepartmentsRouteRoute
  '/invoices': typeof AuthenticatedInvoicesRouteRoute
  '/login-logs': typeof AuthenticatedLoginLogsRouteRoute
  '/menus': typeof AuthenticatedMenusRouteRoute
  '/operation-logs': typeof AuthenticatedOperationLogsRouteRoute
  '/payments': typeof AuthenticatedPaymentsRouteRouteWithChildren
  '/products': typeof AuthenticatedProductsRouteRoute
  '/roles': typeof AuthenticatedRolesRouteRouteWithChildren
  '/service-teams': typeof AuthenticatedServiceTeamsRouteRoute
  '/social-media': typeof AuthenticatedSocialMediaRouteRoute
  '/system-logs': typeof AuthenticatedSystemLogsRouteRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/webhooks': typeof AuthenticatedWebhooksRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/cms/elements': typeof AuthenticatedCmsElementsRouteRoute
  '/cms/new': typeof AuthenticatedCmsNewRouteRoute
  '/cms/pages': typeof AuthenticatedCmsPagesRouteRouteWithChildren
  '/cms/tags': typeof AuthenticatedCmsTagsRouteRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/payments/config': typeof AuthenticatedPaymentsConfigRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/webhooks/templates': typeof AuthenticatedWebhooksTemplatesRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/cms': typeof AuthenticatedCmsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/cms/edit/$id': typeof AuthenticatedCmsEditIdRouteRoute
  '/cms/pages/new': typeof AuthenticatedCmsPagesNewRouteRoute
  '/roles/$roleId/permissions': typeof AuthenticatedRolesRoleIdPermissionsRoute
  '/cms/pages/edit/$pageId': typeof AuthenticatedCmsPagesEditPageIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/setup-2fa': typeof Setup2faRoute
  '/_authenticated/ai-agent': typeof AuthenticatedAiAgentRouteRoute
  '/_authenticated/cms': typeof AuthenticatedCmsRouteRouteWithChildren
  '/_authenticated/contacts': typeof AuthenticatedContactsRouteRoute
  '/_authenticated/contract-templates': typeof AuthenticatedContractTemplatesRouteRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRouteRoute
  '/_authenticated/customer-rules': typeof AuthenticatedCustomerRulesRouteRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRouteRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteRoute
  '/_authenticated/login-logs': typeof AuthenticatedLoginLogsRouteRoute
  '/_authenticated/menus': typeof AuthenticatedMenusRouteRoute
  '/_authenticated/operation-logs': typeof AuthenticatedOperationLogsRouteRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRouteRouteWithChildren
  '/_authenticated/products': typeof AuthenticatedProductsRouteRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRouteRouteWithChildren
  '/_authenticated/service-teams': typeof AuthenticatedServiceTeamsRouteRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/social-media': typeof AuthenticatedSocialMediaRouteRoute
  '/_authenticated/system-logs': typeof AuthenticatedSystemLogsRouteRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/webhooks': typeof AuthenticatedWebhooksRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cms/elements': typeof AuthenticatedCmsElementsRouteRoute
  '/_authenticated/cms/new': typeof AuthenticatedCmsNewRouteRoute
  '/_authenticated/cms/pages': typeof AuthenticatedCmsPagesRouteRouteWithChildren
  '/_authenticated/cms/tags': typeof AuthenticatedCmsTagsRouteRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/payments/config': typeof AuthenticatedPaymentsConfigRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/webhooks/templates': typeof AuthenticatedWebhooksTemplatesRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/cms/': typeof AuthenticatedCmsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/cms/edit/$id': typeof AuthenticatedCmsEditIdRouteRoute
  '/_authenticated/cms/pages/new': typeof AuthenticatedCmsPagesNewRouteRoute
  '/_authenticated/roles/$roleId/permissions': typeof AuthenticatedRolesRoleIdPermissionsRoute
  '/_authenticated/cms/pages/edit/$pageId': typeof AuthenticatedCmsPagesEditPageIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/setup-2fa'
    | '/ai-agent'
    | '/cms'
    | '/contacts'
    | '/contract-templates'
    | '/contracts'
    | '/customer-rules'
    | '/customers'
    | '/departments'
    | '/invoices'
    | '/login-logs'
    | '/menus'
    | '/operation-logs'
    | '/payments'
    | '/products'
    | '/roles'
    | '/service-teams'
    | '/settings'
    | '/social-media'
    | '/system-logs'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/webhooks'
    | '/cms/elements'
    | '/cms/new'
    | '/cms/pages'
    | '/cms/tags'
    | '/errors/$error'
    | '/payments/config'
    | '/settings/account'
    | '/settings/security'
    | '/webhooks/templates'
    | '/apps/'
    | '/chats/'
    | '/cms/'
    | '/help-center/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/cms/edit/$id'
    | '/cms/pages/new'
    | '/roles/$roleId/permissions'
    | '/cms/pages/edit/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/login'
    | '/setup-2fa'
    | '/ai-agent'
    | '/contacts'
    | '/contract-templates'
    | '/contracts'
    | '/customer-rules'
    | '/customers'
    | '/departments'
    | '/invoices'
    | '/login-logs'
    | '/menus'
    | '/operation-logs'
    | '/payments'
    | '/products'
    | '/roles'
    | '/service-teams'
    | '/social-media'
    | '/system-logs'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/webhooks'
    | '/'
    | '/cms/elements'
    | '/cms/new'
    | '/cms/pages'
    | '/cms/tags'
    | '/errors/$error'
    | '/payments/config'
    | '/settings/account'
    | '/settings/security'
    | '/webhooks/templates'
    | '/apps'
    | '/chats'
    | '/cms'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/cms/edit/$id'
    | '/cms/pages/new'
    | '/roles/$roleId/permissions'
    | '/cms/pages/edit/$pageId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/change-password'
    | '/login'
    | '/setup-2fa'
    | '/_authenticated/ai-agent'
    | '/_authenticated/cms'
    | '/_authenticated/contacts'
    | '/_authenticated/contract-templates'
    | '/_authenticated/contracts'
    | '/_authenticated/customer-rules'
    | '/_authenticated/customers'
    | '/_authenticated/departments'
    | '/_authenticated/invoices'
    | '/_authenticated/login-logs'
    | '/_authenticated/menus'
    | '/_authenticated/operation-logs'
    | '/_authenticated/payments'
    | '/_authenticated/products'
    | '/_authenticated/roles'
    | '/_authenticated/service-teams'
    | '/_authenticated/settings'
    | '/_authenticated/social-media'
    | '/_authenticated/system-logs'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/webhooks'
    | '/_authenticated/'
    | '/_authenticated/cms/elements'
    | '/_authenticated/cms/new'
    | '/_authenticated/cms/pages'
    | '/_authenticated/cms/tags'
    | '/_authenticated/errors/$error'
    | '/_authenticated/payments/config'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/security'
    | '/_authenticated/webhooks/templates'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/cms/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/cms/edit/$id'
    | '/_authenticated/cms/pages/new'
    | '/_authenticated/roles/$roleId/permissions'
    | '/_authenticated/cms/pages/edit/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  Setup2faRoute: typeof Setup2faRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-2fa': {
      id: '/setup-2fa'
      path: '/setup-2fa'
      fullPath: '/setup-2fa'
      preLoaderRoute: typeof Setup2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks': {
      id: '/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/system-logs': {
      id: '/_authenticated/system-logs'
      path: '/system-logs'
      fullPath: '/system-logs'
      preLoaderRoute: typeof AuthenticatedSystemLogsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social-media': {
      id: '/_authenticated/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof AuthenticatedSocialMediaRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-teams': {
      id: '/_authenticated/service-teams'
      path: '/service-teams'
      fullPath: '/service-teams'
      preLoaderRoute: typeof AuthenticatedServiceTeamsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operation-logs': {
      id: '/_authenticated/operation-logs'
      path: '/operation-logs'
      fullPath: '/operation-logs'
      preLoaderRoute: typeof AuthenticatedOperationLogsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menus': {
      id: '/_authenticated/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AuthenticatedMenusRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/login-logs': {
      id: '/_authenticated/login-logs'
      path: '/login-logs'
      fullPath: '/login-logs'
      preLoaderRoute: typeof AuthenticatedLoginLogsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer-rules': {
      id: '/_authenticated/customer-rules'
      path: '/customer-rules'
      fullPath: '/customer-rules'
      preLoaderRoute: typeof AuthenticatedCustomerRulesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contract-templates': {
      id: '/_authenticated/contract-templates'
      path: '/contract-templates'
      fullPath: '/contract-templates'
      preLoaderRoute: typeof AuthenticatedContractTemplatesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms': {
      id: '/_authenticated/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AuthenticatedCmsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-agent': {
      id: '/_authenticated/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AuthenticatedAiAgentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/': {
      id: '/_authenticated/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof AuthenticatedCmsIndexRouteImport
      parentRoute: typeof AuthenticatedCmsRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks/templates': {
      id: '/_authenticated/webhooks/templates'
      path: '/templates'
      fullPath: '/webhooks/templates'
      preLoaderRoute: typeof AuthenticatedWebhooksTemplatesRouteImport
      parentRoute: typeof AuthenticatedWebhooksRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/payments/config': {
      id: '/_authenticated/payments/config'
      path: '/config'
      fullPath: '/payments/config'
      preLoaderRoute: typeof AuthenticatedPaymentsConfigRouteImport
      parentRoute: typeof AuthenticatedPaymentsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/tags': {
      id: '/_authenticated/cms/tags'
      path: '/tags'
      fullPath: '/cms/tags'
      preLoaderRoute: typeof AuthenticatedCmsTagsRouteRouteImport
      parentRoute: typeof AuthenticatedCmsRouteRoute
    }
    '/_authenticated/cms/pages': {
      id: '/_authenticated/cms/pages'
      path: '/pages'
      fullPath: '/cms/pages'
      preLoaderRoute: typeof AuthenticatedCmsPagesRouteRouteImport
      parentRoute: typeof AuthenticatedCmsRouteRoute
    }
    '/_authenticated/cms/new': {
      id: '/_authenticated/cms/new'
      path: '/new'
      fullPath: '/cms/new'
      preLoaderRoute: typeof AuthenticatedCmsNewRouteRouteImport
      parentRoute: typeof AuthenticatedCmsRouteRoute
    }
    '/_authenticated/cms/elements': {
      id: '/_authenticated/cms/elements'
      path: '/elements'
      fullPath: '/cms/elements'
      preLoaderRoute: typeof AuthenticatedCmsElementsRouteRouteImport
      parentRoute: typeof AuthenticatedCmsRouteRoute
    }
    '/_authenticated/roles/$roleId/permissions': {
      id: '/_authenticated/roles/$roleId/permissions'
      path: '/$roleId/permissions'
      fullPath: '/roles/$roleId/permissions'
      preLoaderRoute: typeof AuthenticatedRolesRoleIdPermissionsRouteImport
      parentRoute: typeof AuthenticatedRolesRouteRoute
    }
    '/_authenticated/cms/pages/new': {
      id: '/_authenticated/cms/pages/new'
      path: '/new'
      fullPath: '/cms/pages/new'
      preLoaderRoute: typeof AuthenticatedCmsPagesNewRouteRouteImport
      parentRoute: typeof AuthenticatedCmsPagesRouteRoute
    }
    '/_authenticated/cms/edit/$id': {
      id: '/_authenticated/cms/edit/$id'
      path: '/edit/$id'
      fullPath: '/cms/edit/$id'
      preLoaderRoute: typeof AuthenticatedCmsEditIdRouteRouteImport
      parentRoute: typeof AuthenticatedCmsRouteRoute
    }
    '/_authenticated/cms/pages/edit/$pageId': {
      id: '/_authenticated/cms/pages/edit/$pageId'
      path: '/edit/$pageId'
      fullPath: '/cms/pages/edit/$pageId'
      preLoaderRoute: typeof AuthenticatedCmsPagesEditPageIdRouteRouteImport
      parentRoute: typeof AuthenticatedCmsPagesRouteRoute
    }
  }
}

interface AuthenticatedCmsPagesRouteRouteChildren {
  AuthenticatedCmsPagesNewRouteRoute: typeof AuthenticatedCmsPagesNewRouteRoute
  AuthenticatedCmsPagesEditPageIdRouteRoute: typeof AuthenticatedCmsPagesEditPageIdRouteRoute
}

const AuthenticatedCmsPagesRouteRouteChildren: AuthenticatedCmsPagesRouteRouteChildren =
  {
    AuthenticatedCmsPagesNewRouteRoute: AuthenticatedCmsPagesNewRouteRoute,
    AuthenticatedCmsPagesEditPageIdRouteRoute:
      AuthenticatedCmsPagesEditPageIdRouteRoute,
  }

const AuthenticatedCmsPagesRouteRouteWithChildren =
  AuthenticatedCmsPagesRouteRoute._addFileChildren(
    AuthenticatedCmsPagesRouteRouteChildren,
  )

interface AuthenticatedCmsRouteRouteChildren {
  AuthenticatedCmsElementsRouteRoute: typeof AuthenticatedCmsElementsRouteRoute
  AuthenticatedCmsNewRouteRoute: typeof AuthenticatedCmsNewRouteRoute
  AuthenticatedCmsPagesRouteRoute: typeof AuthenticatedCmsPagesRouteRouteWithChildren
  AuthenticatedCmsTagsRouteRoute: typeof AuthenticatedCmsTagsRouteRoute
  AuthenticatedCmsIndexRoute: typeof AuthenticatedCmsIndexRoute
  AuthenticatedCmsEditIdRouteRoute: typeof AuthenticatedCmsEditIdRouteRoute
}

const AuthenticatedCmsRouteRouteChildren: AuthenticatedCmsRouteRouteChildren = {
  AuthenticatedCmsElementsRouteRoute: AuthenticatedCmsElementsRouteRoute,
  AuthenticatedCmsNewRouteRoute: AuthenticatedCmsNewRouteRoute,
  AuthenticatedCmsPagesRouteRoute: AuthenticatedCmsPagesRouteRouteWithChildren,
  AuthenticatedCmsTagsRouteRoute: AuthenticatedCmsTagsRouteRoute,
  AuthenticatedCmsIndexRoute: AuthenticatedCmsIndexRoute,
  AuthenticatedCmsEditIdRouteRoute: AuthenticatedCmsEditIdRouteRoute,
}

const AuthenticatedCmsRouteRouteWithChildren =
  AuthenticatedCmsRouteRoute._addFileChildren(
    AuthenticatedCmsRouteRouteChildren,
  )

interface AuthenticatedPaymentsRouteRouteChildren {
  AuthenticatedPaymentsConfigRoute: typeof AuthenticatedPaymentsConfigRoute
}

const AuthenticatedPaymentsRouteRouteChildren: AuthenticatedPaymentsRouteRouteChildren =
  {
    AuthenticatedPaymentsConfigRoute: AuthenticatedPaymentsConfigRoute,
  }

const AuthenticatedPaymentsRouteRouteWithChildren =
  AuthenticatedPaymentsRouteRoute._addFileChildren(
    AuthenticatedPaymentsRouteRouteChildren,
  )

interface AuthenticatedRolesRouteRouteChildren {
  AuthenticatedRolesRoleIdPermissionsRoute: typeof AuthenticatedRolesRoleIdPermissionsRoute
}

const AuthenticatedRolesRouteRouteChildren: AuthenticatedRolesRouteRouteChildren =
  {
    AuthenticatedRolesRoleIdPermissionsRoute:
      AuthenticatedRolesRoleIdPermissionsRoute,
  }

const AuthenticatedRolesRouteRouteWithChildren =
  AuthenticatedRolesRouteRoute._addFileChildren(
    AuthenticatedRolesRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedWebhooksRouteChildren {
  AuthenticatedWebhooksTemplatesRoute: typeof AuthenticatedWebhooksTemplatesRoute
}

const AuthenticatedWebhooksRouteChildren: AuthenticatedWebhooksRouteChildren = {
  AuthenticatedWebhooksTemplatesRoute: AuthenticatedWebhooksTemplatesRoute,
}

const AuthenticatedWebhooksRouteWithChildren =
  AuthenticatedWebhooksRoute._addFileChildren(
    AuthenticatedWebhooksRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiAgentRouteRoute: typeof AuthenticatedAiAgentRouteRoute
  AuthenticatedCmsRouteRoute: typeof AuthenticatedCmsRouteRouteWithChildren
  AuthenticatedContactsRouteRoute: typeof AuthenticatedContactsRouteRoute
  AuthenticatedContractTemplatesRouteRoute: typeof AuthenticatedContractTemplatesRouteRoute
  AuthenticatedContractsRouteRoute: typeof AuthenticatedContractsRouteRoute
  AuthenticatedCustomerRulesRouteRoute: typeof AuthenticatedCustomerRulesRouteRoute
  AuthenticatedCustomersRouteRoute: typeof AuthenticatedCustomersRouteRoute
  AuthenticatedDepartmentsRouteRoute: typeof AuthenticatedDepartmentsRouteRoute
  AuthenticatedInvoicesRouteRoute: typeof AuthenticatedInvoicesRouteRoute
  AuthenticatedLoginLogsRouteRoute: typeof AuthenticatedLoginLogsRouteRoute
  AuthenticatedMenusRouteRoute: typeof AuthenticatedMenusRouteRoute
  AuthenticatedOperationLogsRouteRoute: typeof AuthenticatedOperationLogsRouteRoute
  AuthenticatedPaymentsRouteRoute: typeof AuthenticatedPaymentsRouteRouteWithChildren
  AuthenticatedProductsRouteRoute: typeof AuthenticatedProductsRouteRoute
  AuthenticatedRolesRouteRoute: typeof AuthenticatedRolesRouteRouteWithChildren
  AuthenticatedServiceTeamsRouteRoute: typeof AuthenticatedServiceTeamsRouteRoute
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSocialMediaRouteRoute: typeof AuthenticatedSocialMediaRouteRoute
  AuthenticatedSystemLogsRouteRoute: typeof AuthenticatedSystemLogsRouteRoute
  AuthenticatedWebhooksRoute: typeof AuthenticatedWebhooksRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiAgentRouteRoute: AuthenticatedAiAgentRouteRoute,
  AuthenticatedCmsRouteRoute: AuthenticatedCmsRouteRouteWithChildren,
  AuthenticatedContactsRouteRoute: AuthenticatedContactsRouteRoute,
  AuthenticatedContractTemplatesRouteRoute:
    AuthenticatedContractTemplatesRouteRoute,
  AuthenticatedContractsRouteRoute: AuthenticatedContractsRouteRoute,
  AuthenticatedCustomerRulesRouteRoute: AuthenticatedCustomerRulesRouteRoute,
  AuthenticatedCustomersRouteRoute: AuthenticatedCustomersRouteRoute,
  AuthenticatedDepartmentsRouteRoute: AuthenticatedDepartmentsRouteRoute,
  AuthenticatedInvoicesRouteRoute: AuthenticatedInvoicesRouteRoute,
  AuthenticatedLoginLogsRouteRoute: AuthenticatedLoginLogsRouteRoute,
  AuthenticatedMenusRouteRoute: AuthenticatedMenusRouteRoute,
  AuthenticatedOperationLogsRouteRoute: AuthenticatedOperationLogsRouteRoute,
  AuthenticatedPaymentsRouteRoute: AuthenticatedPaymentsRouteRouteWithChildren,
  AuthenticatedProductsRouteRoute: AuthenticatedProductsRouteRoute,
  AuthenticatedRolesRouteRoute: AuthenticatedRolesRouteRouteWithChildren,
  AuthenticatedServiceTeamsRouteRoute: AuthenticatedServiceTeamsRouteRoute,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSocialMediaRouteRoute: AuthenticatedSocialMediaRouteRoute,
  AuthenticatedSystemLogsRouteRoute: AuthenticatedSystemLogsRouteRoute,
  AuthenticatedWebhooksRoute: AuthenticatedWebhooksRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  Setup2faRoute: Setup2faRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
